### ISSUE TITLE
Namespace and function names

### ISSUE THREAD

**Issue by ocornut** [mellinoe/ImGui.NET#1]
Hello,
I realize this hasn't really been publicized and is work-in-progress (I stumbled on it yesterday while doing searches).
Thanks for looking into that!

Have only looked briefly, but may I suggest that the `ImGuiNative.igButton()` syntax be changed to something like `ImGui.Button()`. ?
O.

**Comment by mellinoe** [comment]
I'm definitely planning on doing that for all of the imported functions, but right now I'm still trying to make sure all of the native methods are imported correctly, etc. I actually already have an ImGui class that I'm planning on putting the "pretty" methods into:

https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/ImGui.cs

My general idea is that:

* The 'ImGuiNative' class will have all of the raw imported functions in it, and the signatures will be exactly as they appear in the exported function, and the names exactly the same as well.
* The 'ImGui' class will have "wrappers" for the native functions that have simpler parameters and cleaner names, and patterns more familiar to regular C#, like ref parameters, no pointers, etc.

This would let you code with the cleaner API, but still give you the flexibility to fall back to the raw native methods if you needed to for some reason.

Thanks for the wiki link, btw :smile: . I've only just started working on this for a week, so it's still very rough around the edges.

**Comment by mellinoe** [comment]
Closing the loop on this one (2.5 years later 😅): the suggested organization is more or less what I landed on. There's basically two layers in here: The `ImGuiNative` class has all of the raw C functions, which are very messy and unfriendly for regular use. The `ImGui` class has friendly, type-safe wrapper methods for the C functions, but there's still a few niche functions that aren't there.
