### ISSUE TITLE
How to attach to game window

### ISSUE THREAD

**Issue by thgiang** [mellinoe/ImGui.NET#100]
Could you please help me attach my window to game window?
I am trying to use IMGUI to make an overlay window. (Writing a game cheat)

In my mind, it will be 2 methods:
- Create a new window with transparent key then set it is topmost
- Or an other way which IMGUI is supporting (but I dont know) to attach IMGUI to Game Window by IntPtr (Game Window ID)

Please tell me which is is best and how to do it. Thank you very much!

**Comment by thgiang** [comment]
We can make the _window is top most but have no way to make it is transparent.

 _window = new Sdl2Window("NIX", 10, 10, 100, 800, SDL_WindowFlags.Borderless | SDL_WindowFlags.AlwaysOnTop, false);
            GraphicsDevice _gd =  VeldridStartup.CreateGraphicsDevice(_window, new GraphicsDeviceOptions(true, null, true));

**Comment by thgiang** [comment]
@zaafar  Could you please help me make it transparent?

**Comment by zaafar** [comment]
Basically what I am trying to say is, when we make the SDL2Window transparent the SDL_WindowFlags.AlwaysOnTop flag stops working.

I need to dig the code for making the SDL2Window transparent. Will share with you once I find it.

**Comment by zaafar** [comment]
well, good news ... looks like it's working now .. it wasn't few months ago.
Time to go back to creating the overlay. :)
checkout my fork and commit to see how to get the window transparent
https://github.com/zaafar/ImGui.NET/commit/1a0f74062b36430fd2a3f2ad7caa7d0c3f1524c0


BTW @mellinoe  thx for adding the flag. :)

**Comment by thgiang** [comment]
@zaafar  Thank you for your code. I can made it transparent now.
I see this function: EnableTransparent on WinApi.cs
When I use this flag: WS_EX_LAYERED => ImGUI not clickable. I can't click the demo menu
When I remove it, the game not clickable.

Could you please give me a fix?

**Comment by zaafar** [comment]
When you make a window transparent the clicks go through the window too. You need to hook the windows clicks and key presses and pass it to the game/overlay manually. Good luck!

**Comment by thgiang** [comment]
Thank you @zaafar 
I have an idea. If we has an option to click thought ImGUI. It mean one click can effect to ImGUI and the game window too. 

Anyone know how to do it?

**Comment by mellinoe** [comment]
It doesn't sound like there is an easy solution here. I'm not all that familiar with the Win32 API's that allow this, but @zaafar's code looks like what I see recommended around the web. His suggestion to manually propagate the input events to the window underneath sounds like a reasonable workaround if it's not working automatically.

**Comment by thgiang** [comment]
Hi @mellinoe 
I am attaching to old window instead of create a new window. 
This is my code: http://prntscr.com/m4400t

But I see the error as image. How about my idea and how to fix the error?
Thank you.

**Comment by zaafar** [comment]
@thgiang there you go https://github.com/zaafar/ClickableTransparentOverlay
it's work in progress but it's will get you started. feel free to close the issue now. 👍
