### ISSUE TITLE
c# example for ImGuiTextFilter

### ISSUE THREAD

**Issue by zaafar** [mellinoe/ImGui.NET#107]
I was trying to use ImGuiTextFilter but couldn't find a c# example of it. I looked at the ImGui demo code example and tried to replicate that on ImGui.NET but failed. Here's the code I was using, let me know how to use this feature.

```
ImGuiTextFilter testing = new ImGuiTextFilter();
testing.draw()
```

I did find the ImGuiTextFilterPtr struct/class but not sure how to use it.

**reference c++ eample**
```
static ImGuiTextFilter filter;
filter.draw();
        const char* lines[] = { "aaa1.c", "bbb1.c", "ccc1.c", "aaa2.cpp", "bbb2.cpp", "ccc2.cpp", "abc.h", "hello, world" };
        for (int i = 0; i < IM_ARRAYSIZE(lines); i++)
            if (filter.PassFilter(lines[i]))
                ImGui::BulletText("%s", lines[i]);
```

**Comment by mellinoe** [comment]
The C# code generator needs to be augmented to allow constructors for native objects to be called. Without that, there's no current way to create an ImGuiTextFilter. It's not a lot of work to add this functionality to the code generator; the information is already there waiting to be used.

**Comment by SomeAnon42** [comment]
I'm not sure what the generated constructor for ``ImGuiTextFilter`` would look like. Clearly a constructor that simply accepts an ``ImVector`` and an ``int`` would be useless (the struct is mutable anyway, and it's not like there's currently a way to create an ``ImVector``).

**Comment by zaafar** [comment]
Currently, I am not an expert in code generator technique you folks are using :( so I can not modify/update that code but I ported the "AutoComplete" InputBox code from [this](https://github.com/ocornut/imgui/issues/718), [this](https://github.com/ocornut/imgui/issues/1658) and this thread.

**Comment by prime31** [comment]
It turns out this not only affects text filters but also ImFontConfig which needs to be created on the native side. @mellinoe if you can point me in the right direction (brief overview of what needs to be done) I can try to carve out some time to get this going.

**Comment by mellinoe** [comment]
I pushed two changes to master that fix the raw PInvokes for constructor and destructor functions:

https://github.com/mellinoe/ImGui.NET/commit/8e3caa1b49bd6b8df5bb277c52c5bb9c32115813
https://github.com/mellinoe/ImGui.NET/commit/4588142ef950d3e474de5635a99f890b55095570

[Ideally](https://github.com/mellinoe/ImGui.NET/commit/1743198544bb621d3117ba414cee15b1b4f347bd#diff-3cc57daf09241032a319b47f6f387f4eR371), there would be static functions that invoke the native constructor, with default parameters being generated as with other overloads. Right now, you can invoke the functions added in the first commit and get back a raw pointer, which needs to be deleted later with a matching `thing_destroy` call.

Another note: you could already create these structures on the C# side and pass a pointer to them to the native side. Where it gets tricky is:
* ImVector -- The native side will likely try to reallocate the buffer at some point, and things will probably not work. If you preallocate a large enough vector, it might work. This matters for `ImGuiTextFilter` because it contains a vector.
* Default values -- Allocating the struct in C# will zero-init everything, which means it won't have the default values it would have in C++: [for example](https://github.com/ocornut/imgui/blob/master/imgui_draw.cpp#L1357).
* Lifetime -- if you're passing a pointer to the C# object, you need to make sure it remains valid (e.g. not on the stack if it's long-lived).

**Comment by mikedJC** [comment]
Thanks @mellinoe! Works like a champ. For those who find this later here is an `ImFontConfig` example which is very similar to 'ImGuiTextFilter' and should let you know how it all works:

```csharp
// create the object on the native side
var nativeConfig = ImGuiNative.ImFontConfig_ImFontConfig();

// fill with data
(*nativeConfig).OversampleH = 3;
(*nativeConfig).OversampleV = 1;
(*nativeConfig).RasterizerMultiply = 1f;
(*nativeConfig).GlyphExtraSpacing = new Num.Vector2(10, 0);

// use the object
ImGui.GetIO().Fonts.AddFontFromFileTTF("/Library/Fonts/Comic Sans MS.ttf", 16, nativeConfig);

// delete the reference. ImGui copies it
ImGuiNative.ImFontConfig_destroy(nativeConfig);
```

**Comment by mikedJC** [comment]
For the sake of completeness and future visitors, here is an `ImGuiTextFilter` example as well:

```csharp
unsafe public class CleanTest
{
    string[] _lines = { "aaa1.c", "bbb1.c", "ccc1.c", "aaa2.cpp", "bbb2.cpp", "ccc2.cpp", "abc.h", "hello, world" };
    ImGuiTextFilterPtr _filter;

    public CleanTest()
    {
        var filterPtr = ImGuiNative.ImGuiTextFilter_ImGuiTextFilter(null);
        _filter = new ImGuiTextFilterPtr(filterPtr);
    }

    public void Draw()
    {
        ImGui.Begin("Here We Go");

        _filter.Draw("This is a text filter");

        foreach(var line in _lines)
        {
            if (_filter.PassFilter(line))
                ImGui.BulletText(line);
        }

        ImGui.End();
    }

    public void Destroy()
    {
        ImGuiNative.ImGuiTextFilter_destroy(_filter.NativePtr);
    }
}
```

**Comment by mikedJC** [comment]
One last thing for @mellinoe: any chance of a NuGet bump?

**Comment by prime31** [comment]
Sorry about double post. Used the wrong GitHub account.

Thanks @mellinoe! Works like a champ. For those who find this later here is an `ImFontConfig` example which is very similar to 'ImGuiTextFilter' and should let you know how it all works:

```csharp
// create the object on the native side
var nativeConfig = ImGuiNative.ImFontConfig_ImFontConfig();

// fill with data
(*nativeConfig).OversampleH = 3;
(*nativeConfig).OversampleV = 1;
(*nativeConfig).RasterizerMultiply = 1f;
(*nativeConfig).GlyphExtraSpacing = new Num.Vector2(10, 0);

// use the object
ImGui.GetIO().Fonts.AddFontFromFileTTF("/Library/Fonts/Comic Sans MS.ttf", 16, nativeConfig);

// delete the reference. ImGui copies it
ImGuiNative.ImFontConfig_destroy(nativeConfig);
```

Or, using the Ptr wrapper class:

```csharp
// create the object on the native side and wrap it in a C# class
var nativeConfig = ImGuiNative.ImFontConfig_ImFontConfig();
var config = new ImFontConfigPtr(nativeConfig);

// use the object
config.OversampleH = 2;
config.OversampleV = 1;
config.RasterizerMultiply = 1f;

ImGui.GetIO().Fonts.AddFontFromFileTTF("/Library/Fonts/Comic Sans MS.ttf", 16, nativeConfig);

// delete the reference. ImGui copies it
config.Destroy();
```

**Comment by prime31** [comment]
For the sake of completeness and future visitors, here is an `ImGuiTextFilter` example as well:

```csharp
unsafe public class CleanTest
{
    string[] _lines = { "aaa1.c", "bbb1.c", "ccc1.c", "aaa2.cpp", "bbb2.cpp", "ccc2.cpp", "abc.h", "hello, world" };
    ImGuiTextFilterPtr _filter;

    public CleanTest()
    {
        var filterPtr = ImGuiNative.ImGuiTextFilter_ImGuiTextFilter(null);
        _filter = new ImGuiTextFilterPtr(filterPtr);
    }

    public void Draw()
    {
        ImGui.Begin("Here We Go");

        _filter.Draw("This is a text filter");

        foreach(var line in _lines)
        {
            if (_filter.PassFilter(line))
                ImGui.BulletText(line);
        }

        ImGui.End();
    }

    public void Destroy()
    {
        ImGuiNative.ImGuiTextFilter_destroy(_filter.NativePtr);
    }
}
```

**Comment by prime31** [comment]
One last thing for @mellinoe: any chance of a NuGet bump?
