### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by leecannon** [mellinoe/ImGui.NET#111]
I am getting an AccessViolationException upon calling NewFrame/Begin/Render/etc.

On Windows 10 x64 using .NET Core 3 Preview 2, .NET Core 2.1 and .NET Framework 4.7.2

Have tried both x86 and x64

All the statements commented below throw the same exception

## Main Function
 	using ImGuiNET;

	namespace ImGUITest
	{
		internal class Program
		{
			private static void Main()
			{
				var context = ImGui.CreateContext();
				ImGui.SetCurrentContext(context);

				var io = ImGui.GetIO();

				io.Fonts.AddFontDefault();

				ImGui.NewFrame(); // AccessViolationException

				ImGui.Begin("Hello"); // AccessViolationException
				ImGui.Button("World"); // AccessViolationException
				ImGui.End(); // AccessViolationException

				ImGui.Render(); // AccessViolationException
				var stuffToDraw = ImGui.GetDrawData(); // AccessViolationException

				ImGui.DestroyContext(context);
			}
		}
	}

## Project File
	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>netcoreapp3</TargetFramework>
	  </PropertyGroup>

	  <ItemGroup>
		<PackageReference Include="ImGui.NET" Version="1.67.0" />
	  </ItemGroup>

	</Project>

**Comment by mellinoe** [comment]
You are likely skipping some initialization steps that are required. Check out the order in which things are called in the sample code -- something must be missing there.

**Comment by mellinoe** [comment]
To clarify some more, you need to do quite a bit more initialization and setup than your example code. ImGui.NET by itself (much like the native library it wraps) doesn't do any rendering itself; that functionality needs to be added on top of it using some kind of graphics library. The repository here contains two such example renderers, one targeting my [Veldrid](https://github.com/mellinoe/veldrid) library, and the other targeting MonoGame/FNA. Either of those are a good starting point for using the library.

**Comment by leecannon** [comment]
Okay i've correctly setup the font texture now and the code compiles, thanks.

Now time to actually render it :smile:
