### ISSUE TITLE
Are there VB.NET other than C #?

### ISSUE THREAD

**Issue by DongMongppp** [mellinoe/ImGui.NET#112]
I am a user using VB.NET.
You failed to convert C # via Convert.
The reason is that VB.NET does not support pointers.

The UpdateBuffers function had to stop the conversion.
Thanks for posting examples using VB.NET.

please answer about my question.

:)

**Comment by mellinoe** [comment]
Hey @DongMongppp , I'm not really following. Could you be more specific about which portions of the code are difficult to port to VB.NET? It's been a while since I used VB.NET, so I'm a little rusty as to the differences.

**Comment by mellinoe** [comment]
I'm not sure what the question is; feel free to re-open if you can clarify.
