### ISSUE TITLE
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: cimgui

### ISSUE THREAD

**Issue by TheRealNOIG** [mellinoe/ImGui.NET#113]
I saw your solution to this problem in #57 but I cant figure out how to get the dll to point to the linux .so file instead of the dll

**Comment by mellinoe** [comment]
If you are using .NET Core, things should work automatically on Windows, macOS, and Linux. I highly recommend using .NET Core if it's an option for you.

If you need to use mono, then it doesn't work as automatically. The easiest path to success is to just manually copy the .so file (which is included in the NuGet package, or in this repository) next to your compiled program. I would like to make this process automatic, as it is on .NET Core, but it's been a lot lower priority for me for a few reasons.

**Comment by TheRealNOIG** [comment]
Unfortunately, I am unable to us .NET Core. Ive tried placing the .so and .dll in the dir of the compiled program. This works fine for Windows but on Linux I still get the same error. I think DLL maps (https://www.mono-project.com/docs/advanced/pinvoke/dllmap/) should fix my issue but unfortunately I need to head to work so I wont be able to look into this until tomorrow at the earliest.
Ill update this thread if this solves the issue

**Comment by mellinoe** [comment]
@TheRealNOIG Just curious: have you tested the new 1.68 version? This should be fixed as long as you reference the nuget package.
