### ISSUE TITLE
Using a new font causes "System.AccessViolationException"

### ISSUE THREAD

**Issue by Hi-ImKyle** [mellinoe/ImGui.NET#117]
Adding the font seems to cause no issue other than when using the `ImGui.ShowFontSelector();` method shows the new font to be called `<unknown>`, something that doesn't bother me as I want don't want the font to be selected during runtime by the user, I just want it to be set and not changed throughout. 

I'm adding the font with the method `ImGui.GetIO().Fonts.AddFontFromFileTTF(@"C:\Windows\Fonts\Arial.ttf", 12f);`

When trying to change the font to the `<unknown>` font via the font selector for the sake of testing, the program crashes with the `System.AccessViolationException` caused by `ImGuiNative.igNewFrame(); Line 8991 - File ImGui.gen.cs`.

Am I doing something wrong, is this a ImGui.NET issue or an imgui issue, of which I will forward to the imgui github instead of here.

**Comment by Hi-ImKyle** [comment]
I'd like to add that the XNA Sample also seems to follow the same issue. (My environment is XNA, forgot to mention)

**Comment by prime31** [comment]
See the example I posted over [here](https://github.com/mellinoe/ImGui.NET/issues/107#issuecomment-467146191). I am using that code with MonoGame/FNA and its been working fine for me.

**Comment by Hi-ImKyle** [comment]
Doesn't seem to work, outcome is just the same as I've explained.

**Comment by sqrMin1** [comment]
@Hi-ImKyle I'm using the same technique as @prime31 in a XNA/MonoGame project to load different fonts and it also works for me without errors.

Try adding the code from @prime31 in the demo project.

It's worth mentioning that you need to rebuild the FontAtlas **after** adding the fonts.

Steps:

1. Add font like @prime31 described
2. Rebuild font atlas like this: `_imGuiRenderer.RebuildFontAtlas();`

Do this steps in the initialization process after the ImGuiRenderer was instantiated.

I also successfully tried MergeMode which merges multiple font files together.

**Comment by Hi-ImKyle** [comment]
> 2. Rebuild font atlas like this: `_imGuiRenderer.RebuildFontAtlas();`

Not once, at all, did this occur to me. Human errors. I'm not the brightest, but thankfully you are. Thank you @sqrMin1

**Comment by Kein** [comment]
Getting the same issue with crashes on font  and I'm not using ImguiRenderer since I dont use XNA.
