### ISSUE TITLE
Error Unsafe Context

### ISSUE THREAD

**Issue by msmshazan** [mellinoe/ImGui.NET#12]
@mellinoe
I get this error while building the project.
Using .Net Framework 4.6

CS0103	The name 'Unsafe' does not exist in the current context	Imgui.NET c:\Users\Magic DPI\Documents\Visual Studio 2015\Projects\Imgui-FNA\Imgui.NET\TextInputBuffer.cs	49

**Comment by mellinoe** [comment]
Hey @msmshazan, this means that you haven't restored one of the NuGet packages that ImGui.NET relies on, [System.Runtime.CompilerServices.Unsafe](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/). If that assembly is available, the error will go away.

**Comment by msmshazan** [comment]
OK done
