### ISSUE TITLE
how do I use this library?

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/ImGui.NET#123]
how do I use this library? 
I cannot find any documentation on how to use this.
this is what I have tried..
![image](https://user-images.githubusercontent.com/2453707/57895500-d4617280-7800-11e9-92d4-1c8b71fcbfe1.png)

**Comment by keeganatorr** [comment]
Download the solution provided and have a look at how the sample projects work.
The documentation for this library is quite spare, have a look at the demo window to see what is possible.
And read through the C++ code to learn what code does what: https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp

**Comment by mellinoe** [comment]
@keeganatorr has a good suggestion. It's true that there isn't extensive documentation, but you should be able to follow along with the sample projects in this repository to get a feel for how things work. Past that, it's a good idea to check out the original C++ library's documentation (inside the source files). The usage of the C# wrapper is nigh-identical to the C++ version.

Happy to answer any more specific questions if you follow along with the samples and hit a snag.
