### ISSUE TITLE
How can i go about hooking ImGui to an application using C#?

### ISSUE THREAD

**Issue by renewablezip01** [mellinoe/ImGui.NET#129]
I was wondering how you can hook ImGui to a application using C#. Does it work the same way as C++? Or is there any code differences between them that i have look take into account?

I don't really know how to go about it to figure out what to do. If someone could answer this question it would be really helpful. Thank you :)

Edit: Most tutorials I have seen use C++

**Comment by mellinoe** [comment]
Most of the differences from C++ are in the startup and initialization code. The C++ code you have seen likely uses the bundled example renderers (for SDL2/GLFW/Win32/etc.).There are two example projects in this repository that use my graphics library Veldrid, and MonoGame to host ImGui. If you have more specific questions about what is happening in those example projects I can provide more guidance.

**Comment by mellinoe** [comment]
If you look through the example code and have any specific questions, please re-open or follow up with a new issue.
