### ISSUE TITLE
OpenGL implementation?

### ISSUE THREAD

**Issue by GkqqNkKC** [mellinoe/ImGui.NET#131]
Does the OpenGL implementation is ported there too? I use SFML. I can make the binds for events on my own, but I wouldn't like to bother with actual drawing code. Maybe I just missed the name? In the C++ version the functions are like `ImGui_ImplOpenGL3_Init()`. If no implementation is there, are there alternatives?

**Comment by dpethes** [comment]
There was an OpenGL implementation in SampleProgram several revisions ago (using OpenTK, before switching to Veldrid), try checking out an older version for an inspiration.

**Comment by mellinoe** [comment]
> If no implementation is there, are there alternatives?

The alternative is to implement them in C#. Those functions are pretty simple, and depending on what OpenGL bindings you are using, copy-pasting them into a C# file will get you 80-90% of the way to functioning code.

I'd be happy to support an OpenGL example renderer, as long as it ran on Windows+Mac+Linux and didn't have cumbersome dependencies (e.g. everything could be easily pulled through NuGet) or build steps.

**Comment by GkqqNkKC** [comment]
Thx.

**Comment by giawa** [comment]
I hacked together a working (as far as I can tell) OpenGL implementation a little while ago.  I formatted it to look like a sample program in the ImGui.NET repository.  You can check it out here if you're interested:  https://github.com/giawa/ImGui.NET/tree/feature/opengl-sample  I haven't tried it on other platforms, but I don't see why it wouldn't work.
