### ISSUE TITLE
Unable to Render Icon Fonts

### ISSUE THREAD

**Issue by Zeenobit** [mellinoe/ImGui.NET#134]
Hello,

I'd like to know the status of support for Icon Fonts in ImGui.NET. I've been looking all over the web with no luck.

This is how I'm currently trying to load the font:

```cs
ImGui.GetIO().Fonts.AddFontDefault();

unsafe
{
    ImFontConfig fontConfig = new ImFontConfig()
    {
        MergeMode = 1,
        PixelSnapH = 1
    };

    GCHandle rangeHandle = GCHandle.Alloc(new ushort[]
    {
            IconFonts.MaterialDesignIcons.IconMin,
            IconFonts.MaterialDesignIcons.IconMax,
            0
    }, GCHandleType.Pinned);

    try
    {
        ImGui.GetIO().Fonts.AddFontFromFileTTF("./Fonts/" + IconFonts.MaterialDesignIcons.FontIconFileName, 16.0f, &fontConfig, rangeHandle.AddrOfPinnedObject());
    }
    finally
    {
        if (rangeHandle.IsAllocated)
            rangeHandle.Free();
    }
}
```
And this seems to load the font correctly (I have tested this with `ImGui.ShowFontSelector()`). But none of the glyphs render. For example, if I do this:

```
ImGui.Text(IconFonts.MaterialDesignIcons.Account);
```

The glyph doesn't render. Am I not loading the font correctly, or is this not supported for ImGui.NET specifically?

**Comment by mellinoe** [comment]
Hm, if they are showing up in the font selector, then it seems likely that the `ImGui.Text()` call isn't including the right character that you expect. Are you able to inspect the string in a debugger or otherwise double-check that you are including what you want?

**Comment by Zeenobit** [comment]
Finally managed to get it working.

I think it had something to do with the way I was allocating `ImFontConfigPtr`.
Either way, here's the function in case anyone else runs into trouble:

```cs
static unsafe ImFontPtr LoadIconFont(string name, int size, (ushort, ushort) range)
{
    ImFontConfigPtr configuration = ImGuiNative.ImFontConfig_ImFontConfig();

    configuration.MergeMode  = true;
    configuration.PixelSnapH = true;

    string path = Path.Combine(".", "Resources", "Fonts", name + ".ttf");

    GCHandle rangeHandle = GCHandle.Alloc(new ushort[]
    {
        range.Item1,
        range.Item2,
        0
    }, GCHandleType.Pinned);

    try
    {
        return ImGui.GetIO().Fonts.AddFontFromFileTTF(path, size, configuration, rangeHandle.AddrOfPinnedObject());
    }
    finally
    {
        configuration.Destroy();

        if (rangeHandle.IsAllocated)
        {
            rangeHandle.Free();
        }
    }
}```

**Comment by krulci** [comment]
> Finally managed to get it working.
> 
> I think it had something to do with the way I was allocating `ImFontConfigPtr`. Either way, here's the function in case anyone else runs into trouble:
> 
> ```cs
> static unsafe ImFontPtr LoadIconFont(string name, int size, (ushort, ushort) range)
> {
>     ImFontConfigPtr configuration = ImGuiNative.ImFontConfig_ImFontConfig();
> 
>     configuration.MergeMode  = true;
>     configuration.PixelSnapH = true;
> 
>     string path = Path.Combine(".", "Resources", "Fonts", name + ".ttf");
> 
>     GCHandle rangeHandle = GCHandle.Alloc(new ushort[]
>     {
>         range.Item1,
>         range.Item2,
>         0
>     }, GCHandleType.Pinned);
> 
>     try
>     {
>         return ImGui.GetIO().Fonts.AddFontFromFileTTF(path, size, configuration, rangeHandle.AddrOfPinnedObject());
>     }
>     finally
>     {
>         configuration.Destroy();
> 
>         if (rangeHandle.IsAllocated)
>         {
>             rangeHandle.Free();
>         }
>     }
> }
> ```

![image](https://github.com/ImGuiNET/ImGui.NET/assets/52474054/b70e8453-f5b8-42a9-9424-c8ce007d001b)
I tried your solution and show up as unknown in Style Editor.
I am using FontAwesome6
[https://github.com/juliettef/IconFontCppHeaders/blob/main/IconsFontAwesome6.cs](url)

**Comment by Sharkgamedev** [comment]
@krulci Are you using XNA/Monogame? If so you need to call RebuildFontAtlas() after the fact.
