### ISSUE TITLE
Using Imgui.Image

### ISSUE THREAD

**Issue by enquel** [mellinoe/ImGui.NET#141]
First of all, thank you for this great port. I find the code very professional.

My question is - how do I render ImageSharp texture to an ImGui window (Veldrid implementation)? From what I checked I need a pointer stored/handled by the controller, generated via resource factory and converting ImageSharp texture to a Veldrid-compatible resource? Sorry for asking, but XNA example is more clear, it would help to have some Veldrid samples as well (or maybe there are, only I could not find them?).

Best regards

**Comment by enquel** [comment]
Anyway, solved it. Understood the texture must be created in the context of the rendering engine. This issue helped: https://github.com/mellinoe/veldrid/issues/188

I am closing this.

**Comment by KyodaiKen** [comment]
I know this is closed but it works well for me. Except that I can't figure out how to change the resampling filter. It seems to be nearest neighbor and it looks really crappy. How can I change it?
