### ISSUE TITLE
How to use DragFloat3?

### ISSUE THREAD

**Issue by NovemberDev** [mellinoe/ImGui.NET#149]
There is currently no example of DragFloat3 out in the wild. 
The constructor takes a single float, which makes no sense in my eyes if you have 3 float inputs.

So how does it work?

**Comment by mellinoe** [comment]
DragFloat3 takes a `ref Vector3` which should be fairly self-explanatory. Can you explain more what you’re looking for?

**Comment by NovemberDev** [comment]
You are absolutely right, I'm not sure how i overlooked this >-<

Sorry for bothering you with that!
