### ISSUE TITLE
dragint3 and other "combined" widgets taking a ref int instead of an int[3]

### ISSUE THREAD

**Issue by se5a** [mellinoe/ImGui.NET#150]
Somone was asking about dragint3 with imgui.net in the dear imgui discord the other day, and I started looking into it. 

the relevent cimgui call is here:
https://github.com/cimgui/cimgui/blob/master/cimgui.cpp#L692
```
CIMGUI_API bool igDragInt3(const char* label,int v[3],float v_speed,int v_min,int v_max,const char* format)
{
    return ImGui::DragInt3(label,v,v_speed,v_min,v_max,format);
}
```
it appears older versions of imgui.net used an int3 struct to pass the value. however newer versions are using ref int, from the generated code here:
```
fixed (int* native_v = &v)
{
    byte ret = ImGuiNative.igDragInt3(native_label, native_v, v_speed, v_min, v_max, native_format);
    if (label_byteCount > Util.StackAllocationSizeLimit)
    {
        Util.Free(native_label);
    }
    if (format_byteCount > Util.StackAllocationSizeLimit)
    {
        Util.Free(native_format);
    }
    return ret != 0;
}
```

Is this the generated code getting messing something up or am I missing something?

This would be the relevant section in the generator?:
https://github.com/mellinoe/ImGui.NET/blob/master/src/CodeGenerator/Program.cs#L781

**Comment by mellinoe** [comment]
To use this one, you need to pass a reference to the first of a sequence of 3 ints. There's no standard "Int3" type in .NET, so I just chose to not define one and leave that up to the user.

```C#
struct Int3
{
int X, Y, Z;
}

Int3 example;
if (ImGui.DragInt3("Test", ref example.X, ...))
{
    // Value changed.
}
// Additionally:
int[] arr = new int[3];
if (ImGui.DragInt3("Test", ref arr[0], ...))
{
    // Value changed.
}
```

**Comment by se5a** [comment]
wait that works?
I guess I can see how the first item in an array would, but I had no idea a struct would... I guess if I think about how it'd be in memory it a bit more it makes sense.
