### ISSUE TITLE
Getting ImGUI.NET to work with GFLW

### ISSUE THREAD

**Issue by Revolt64** [mellinoe/ImGui.NET#151]
Using this version of GFLW for .NET Core: https://github.com/ForeverZer0/glfw-net

Has anyone managed to integrate it with ImGui.NET ? Specifically, the ImGuiRenderer.cs class. I've googled for ages and can't seem to find any examples.

Thank you.

**Comment by RUSshy** [comment]
GLFW is Window/Input, nothing to do with graphics, if you use OpenGL, try this https://github.com/prime31/ImGuiGL-Renderer, it uses SDL but you can swap with GLFW easily

**Comment by Revolt64** [comment]
> GLFW is Window/Input, nothing to do with graphics, if you use OpenGL, try this https://github.com/prime31/ImGuiGL-Renderer, it uses SDL but you can swap with GLFW easily

That seems to be exactly what I was looking for. Thank you
