### ISSUE TITLE
[docking] Window cannot be dragged out of current monitor

### ISSUE THREAD

**Issue by garyng** [mellinoe/ImGui.NET#157]
In the docking branch, the window cannot be dragged out of the current monitor:

![2020-03-24_21-48-38](https://user-images.githubusercontent.com/4453664/77432626-4808de80-6e19-11ea-9a5a-6f29a6774d20.gif)

**Comment by mellinoe** [comment]
This is working for me. Have you changed anything about the sample program, or have you built the native DLL yourself, or anything like that? The only other difference I note is that your "first monitor" is on the right, and your "second" is on the left. Mine are the opposite, and I wonder if that has anything to do with it. Alternatively, there is [this issue](https://github.com/ocornut/imgui/issues/2176) which describes some potential problems relating to different DPIs across monitors. Does any of that sound like it might affect you?

![imgui_docking_monitors](https://user-images.githubusercontent.com/8918977/77491914-4d0b6500-6dfc-11ea-9e37-66ab4af27aec.gif)

**Comment by garyng** [comment]
The only thing I changed is I removed vulkan as the preferred backend (I can't make it run with vulkan though).

After some experiments, I think the arrangement of monitors do make a difference! This is the my setup:
![image](https://user-images.githubusercontent.com/4453664/77504028-2ef44200-6e9a-11ea-86e3-b8798908b4ae.png)

1: 1920x1080
2: 2560x1080
3: 1080x1920

I couldn't move my window from 1 to 3, or 2 to 3:
![2020-03-25_13-19-37](https://user-images.githubusercontent.com/4453664/77504484-70d1b800-6e9b-11ea-96dc-6fb3982b74e3.gif)
 
![2020-03-25_13-21-19](https://user-images.githubusercontent.com/4453664/77504546-9232a400-6e9b-11ea-8b8e-97181780c5a7.gif)

Seems like the monitor boundary is calculated wrongly?
![2020-03-25_13-29-41](https://user-images.githubusercontent.com/4453664/77504937-b478f180-6e9c-11ea-830b-d1869c9832da.gif)

Weirdly, I cant even move the window out of the main viewport on monitor 3 (the horizontal one):

![2020-03-25_13-24-21](https://user-images.githubusercontent.com/4453664/77504679-fce3df80-6e9b-11ea-97b9-4dfb3ed4ccbc.gif)

This is the metric window showing the monitors info:
![image](https://user-images.githubusercontent.com/4453664/77504791-4df3d380-6e9c-11ea-9833-7952a0225fe9.png)

It only shows 2 monitors instead of 3...

**Comment by garyng** [comment]
So monitor 3 was missing from the monitors list, this is probably the cause instead of the monitor arrangement.

**Comment by mellinoe** [comment]
Can you try out the latest change in the docking branch that I just pushed?

https://github.com/mellinoe/ImGui.NET/commit/69ffb61fab4a9f06a00d86ca1fd7dcc74ffb192e

**Comment by garyng** [comment]
Yeah, it works now! A quick fix!

Thanks!
