### ISSUE TITLE
Upgrade to .net core 3.1

### ISSUE THREAD

**Issue by richardlalancette** [mellinoe/ImGui.NET#166]
I was wondering if you wouldn't mind upgrading imgui net to .net core 3.1?

I have been upgrading on my local branch, but that means a rebase on each update.

Richard.

**Comment by AndrewRublyov** [comment]
I think you could made a PR with changes you made in local branch

**Comment by mellinoe** [comment]
ImGui.NET targets .NET Standard 2.0. It should already support .NET Core 3.1, and I've used it as-is in .NET Core 3.1 projects. You shouldn't need to make any local changes for this.

**Comment by matthiasgrumet** [comment]
i can confirm that it runs in a .net core 3.1 project. however together with the newly released OpenTK 4 (pre release) it seems that the texcoords and colors are mixed up.

**Comment by mellinoe** [comment]
@matthiasgrumet That's most likely a problem with the renderer, not with ImGui.NET. Nothing about the vertices generated by ImGui has changed.

**Comment by Cyphall** [comment]
I confirm that it works with the latest preview of OpenTK (4.0.0-pre9.1).
Note that I'm only using the GL & GLFW bindings from OpenTK, together with adapted versions of the original ImGui implementations for OpenGL3 & GLFW.

**Comment by matthiasgrumet** [comment]
@Cyphall which renderer are you using? personally i used https://github.com/NogginBops/ImGui.NET_OpenTK_Sample with modifications to support OTK4.

**Comment by Cyphall** [comment]
@matthiasgrumet As stated, I'm using modified versions of the official [OpenGL3](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl3.cpp) (for rendering) & [GLFW](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_glfw.cpp) ImGui implementations

**Comment by richardlalancette** [comment]
Exciting!
I've been looking for Xamarin alternative to build simple ui with C#.

We do quarterly hackday at work, and I'm going to use your work to build a small Store Front End for my next hack :)

Love your work Eric! Thank you!

**Comment by richardlalancette** [comment]
Going to close this since upgrade is very trivial.

I have upgraded to .net core 5.0 today and it was piece of cake :)
