### ISSUE TITLE
Remove System.Numerics dependency

### ISSUE THREAD

**Issue by dpethes** [mellinoe/ImGui.NET#17]
I'm maintaining a fork for .Net 4.0, which means I can't use System.Numerics. Therefore I replaced it with custom basic ImVec[234] structs (which also seems to me to follow the original's spirit). Would you accept this change? It would be a tremendous help for sychronizing between the projects.

**Comment by mellinoe** [comment]
Are you not able to simply call your structures "Vector2/3/4/" ? I expect that you could just add an extra .cs file to the project which defines the missing types. Is that not feasible?

**Comment by dpethes** [comment]
The other way around? Sure, that would work. It means a bit more work when converting function declarations from c/imgui, but that's quite minor.

One more minor thing for now - I translated the ImGuiListClipper and I noticed that some structs and their native versions are kept in one file like DrawList + NativeDrawList (which I followed with the Clipper) and some are separated, like Style + NativeStyle. Which do you prefer / should I clean it up?

**Comment by mellinoe** [comment]
> The other way around? Sure, that would work. It means a bit more work when converting function declarations from c/imgui, but that's quite minor.

I was thinking that you wouldn't need to make any changes to ImGuiNative at all, and you could just define your own structures in a different file. Or is the problem that you'd like to call them ImVec2/3/4? In theory we could add a conditional `using` statement at the top of the file, but that might get annoying.

> Which do you prefer / should I clean it up?

I think I'd rather they be in the same file.

**Comment by dpethes** [comment]
> I was thinking that you wouldn't need to make any changes to ImGuiNative at all, and you could just define your own structures in a different file. Or is the problem that you'd like to call them ImVec2/3/4? In theory we could add a conditional using statement at the top of the file, but that might get annoying.

I defined my own Vector2/3/4 but I have to remove the using System.Numerics; line from every source where it's used as well. I can't think of any way to get rid of it (except using define/ifdef, which I don't like). However it isn't that much pain after all, if I keep Vector name instead of ImVec.

**Comment by mellinoe** [comment]
There's a couple ways you could go about it, I think:

* Add the #if's around each file. Kind of annoying that you have to put it in every file.
* Define an internal dummy type in System.Numerics somewhere in your projects so the "using" statements are satisfied. Kind of "hacky", but hey it works.

Would you be interested in having your net40 configuration buildable from the main repo here? I would be happy to support an additional build configuration if there are only very small differences like this.

**Comment by dpethes** [comment]
I like the second option!
The differences in imgui.net should be minimal - can't think of anything else besides Vectors. I'm aiming for usage with WinForms though, so the sample project is completely different. And it needs a software rasterizer as well, which isn't quite ready and mixing its development with imgui.net doesn't quite feel right.
Maybe after I'm mostly done with it?

**Comment by dpethes** [comment]
Actually there is one other thing: ArrayPool in DrawList.AddText. Where does that come from?

**Comment by mellinoe** [comment]
ArrayPool is another new library from https://github.com/dotnet/corefx. It does not support .NET 4.0 either. It should be very trivial to replace it, though:

* Just allocate a new array on every call -- creates lots of garbage.
* Use stack allocation for appropriate sizes and fall back to arrays.
* Use a persistent array, or a thread-static array, or something like that. Essentially implement our own buffer caching / re-use.

Actually, the current usage of ArrayPool is buggy, because I'm not returning the rented buffer. This is the equivalent of allocating a new array on every call. I'll fix that now.

**Comment by mellinoe** [comment]
Oops -- didn't mean to close.

**Comment by dpethes** [comment]
The first option is basically what I do in the text_improvement branch in UTF8 functions with strings (1 temp array per string, even resized once): the effect is negligible, working set in task manager is stable around 80MB on Windows 7, 64bit, .Net4 + OpenTK 2.0. I _think_ the GC can handle such short lived allocations well.

I'd go for the simplest solution first and I guess you have some use-case for it already, so you could easily see the effect.

**Comment by mellinoe** [comment]
I don't have any plans to change how vectors are marshalled. Now that the code is automatically generated it is, however, much easier to generate a version that uses a different vector type.
