### ISSUE TITLE
How do I upgrade to docking?

### ISSUE THREAD

**Issue by BJDubb** [mellinoe/ImGui.NET#176]
I tried to manually build the cimgui into ImGui.NET and nothing has worked. Can anybody please point me in the right direction. I just want to use the docking lib but this is so confusing to me. Im a complete noob with this sort of stuff so any help will be greatly appreciated.

Thanks

**Comment by nik1t0zz** [comment]
You do the same thing as in cpp version of ImGui.
Check out the docking branch and, if you're using Veldrid, add this to Veldrid.ImGui.ImGuiRenderer constructor:

```
ImGui.GetIO().ConfigFlags |= ImGuiConfigFlags.DockingEnable; // new

ImGui.NewFrame(); // old
_frameBegun = true;
```
If you are not using Veldrid then add it in equivalent place.

**Comment by mellinoe** [comment]
The latest version of the package is now using the docking branch by default: https://www.nuget.org/packages/ImGui.NET/1.78.0

Note that the docking feature is not enabled by default. Use this to enable it:

```C#
ImGui.GetIO().ConfigFlags |= ImGuiConfigFlags.DockingEnable;
```

**Comment by Thraka** [comment]
How do we get the dock builder API though? Everything I find on the ImGui forums related to docking use the dockbuilder and I can't figure a lot of stuff out.

**Comment by Shadowblitz16** [comment]
@mellinoe can you anwser @Thraka 's question? I am also wondering.
