### ISSUE TITLE
Add missing native imports and remove "duplicates"

### ISSUE THREAD

**Issue by mellinoe** [mellinoe/ImGui.NET#18]
Currently, ImGui.NET is very close to having full coverage of all cimgui exports for version 1.49. I did a quick diff and identified the following list of functions that are not yet imported. There are also a few functions in `ImGuiNative` that define helper overloads which call the actual imported function. IMO, there should only be a single import for each cimgui function, and helper overloads should go into the `ImGui` class, which is supposed to have the safe, friendly wrappers.

@dpethes Did you mention that you were working on TreeNode stuff? I think I am going to try to finish all of the below before I start handling the 1.50 upgrade and breaking changes.

# ~~Missing imports~~ (Added in 93f9e60dafe179ec1c584f369db32b522ec5f674)

* igCreateContext
* igDestroyContext
* igGetColorU32
* igGetColorU32Vec
* igGetCurrentContext
* igGetFontTexUvWhitePixel
* igGetKeyIndex
* igGetTreeNodeToLabelSpacing
* igIsItemClicked
* igIsRootWindowOrAnyChildHovered
* igNewLine
* igPlotHistogram2
* igPlotLines2
* igProgressBar
* igSetCurrentContext
* igSetItemAllowOverlap
* igSetNextWindowSizeConstraints
* igTreeAdvanceToLabelPos
* igValueColor
* igValueColor2
* ImFontConfig_DefaultConstructor
* ImGuiIO_ClearInputCharacters

# Use va_list or ... (problematic)
* igBulletTextV
* igLabelTextV
* igSetTooltipV
* igTextColoredV
* igTextDisabledV
* igTextV
* igTextWrappedV
* igTreeNodePtrV
* igTreeNodeStrV
* igTreeNodeExV
* igTreeNodeExPtr
* igTreeNodeExStr
* igTreeNodeExVPtr

I think we should ignore the above. You can just use string.Format() and pass that to the single-string overload.

# Duplicate imports

* ImFontAtlas_AddFontDefault
* igSliderFloat
* igBeginPopupModal (x2)

**Comment by mellinoe** [comment]
As part of this analysis I identified a few glaring problems and fixed them with https://github.com/mellinoe/ImGui.NET/commit/aef6b98bdb506bd8c2c6222474d24971a978cf46.

**Comment by mellinoe** [comment]
I added the missing imports in 93f9e60dafe179ec1c584f369db32b522ec5f674, and published version 0.2.0 onto NuGet.

**Comment by dpethes** [comment]
Agreed about va_list. I added the FontAtlas_GetGlyph... functions in my text improvement branch, that should cover most of the FontAtlas imports as well.

**Comment by mellinoe** [comment]
Ah, those must have been added after the cimgui commit I'm using. I'll probably re-do the analysis with version 1.50 this week, and add the new functions. I don't think there is a ton of new stuff, so it shouldn't take too long.

**Comment by dpethes** [comment]
There aren't many, but there are some important changes in IO struct, which can break stuff easily.

**Comment by dpethes** [comment]
I think this can be closed.

**Comment by mellinoe** [comment]
We have complete coverage in the current version we are targeting (1.50), although there are some new functions and breaking changes in 1.51.
