### ISSUE TITLE
InputInt2 and so on, the parameter is not array.

### ISSUE THREAD

**Issue by damarindra** [mellinoe/ImGui.NET#181]
InputInt2 not passing an array, which always fails to create more than one input for int type. Please give me a clue to fix this. I might be can fix it for you, but I don't understand the generator

**Comment by Xeeynamo** [comment]
I proposed the following change to fix the issue: https://github.com/mellinoe/ImGui.NET/pull/182

**Comment by damarindra** [comment]
Isn't the fix supposed to change the Generator? not the gen.cs?

**Comment by mellinoe** [comment]
You can do this with the existing overload. Just pass a reference to the first element in your array (or any other continuously allocated buffer) and it will work. This is how the entire library is bound, and isn’t specific to this function.

**Comment by Xeeynamo** [comment]
I confirm it's working! It's tricky because you have to know how internally works to know it works in that way and why:
```
var loopPair = new int[] { animationGroup.LoopStart, animationGroup.LoopEnd };
if (ImGui.InputInt2("Loop frame", ref loopPair[0]))
{
    animationGroup.LoopStart = loopPair[0];
    animationGroup.LoopEnd = loopPair[1];
}
```

**Comment by damarindra** [comment]
Omg, sorry for my stupidity, thanks!
