### ISSUE TITLE
generator crash for latest imgui

### ISSUE THREAD

**Issue by betabinwang** [mellinoe/ImGui.NET#188]
first may be an expression

![image](https://user-images.githubusercontent.com/13993221/87397933-bac7e080-c5e7-11ea-82e6-6e96d778974b.png)

![image](https://user-images.githubusercontent.com/13993221/87398082-f95d9b00-c5e7-11ea-9828-22daa5536825.png)

![image](https://user-images.githubusercontent.com/13993221/87398041-e945bb80-c5e7-11ea-9602-0e1e50e9c899.png)

**Comment by mellinoe** [comment]
This should be fixed now.
