### ISSUE TITLE
I get many errors "Unable to find an entry point named" with Im.GuiNet.DirectX v1.75.1

### ISSUE THREAD

**Issue by dominota** [mellinoe/ImGui.NET#189]
Hi,
Today, I get the same errors in some functions of ImGui.Net.DirectX 1.75.1

`System.EntryPointNotFoundException: 'Unable to find an entry point named 'igPushStyleColor' in DLL 'cimgui'.'
System.EntryPointNotFoundException: 'Unable to find an entry point named 'igGetMousePos_nonUDT2' in DLL 'cimgui'.'
System.EntryPointNotFoundException: 'Unable to find an entry point named 'igBeginChild' in DLL 'cimgui'.'
System.EntryPointNotFoundException: 'Unable to find an entry point named 'igSelectable' in DLL 'cimgui'.'
...`
Has anyone encountered this error like me?

**Comment by dpethes** [comment]
Where is your cimgui from?

**Comment by dpethes** [comment]
Seems there's a mismatch of cimgui.dll and the generated code in ImGui.Net.DirectX. Try the dlls from ImGui.Net package

**Comment by dominota** [comment]
@dpethes Thanks, i installed ImGui.Net.DirectX from Nuget : [https://www.nuget.org/packages/ImGui.NET.DirectX/1.75.1](url)

**Comment by mellinoe** [comment]
@dominota That looks to be a forked version of the code published by someone else. As such, I can't really help much with it; I'd suggest using the official ImGui.NET package instead: https://www.nuget.org/packages/ImGui.NET/
