### ISSUE TITLE
Update to imgui 1.50

### ISSUE THREAD

**Issue by mellinoe** [mellinoe/ImGui.NET#19]
There isn't a ton of stuff that needs to be done. I have a branch with it done here:

https://github.com/mellinoe/ImGui.NET/tree/1.50

**Comment by dpethes** [comment]
Looks ok except the one comment. I'll post the ListClipper struct / Memory editor improvements after this is merged. Cimgui binaries should be updated as well - let me know if you need windows binaries, I have uploaded both Debug and Release versions.

**Comment by dpethes** [comment]
Could you please merge this? I think nothing is blocking it.

**Comment by mellinoe** [comment]
@dpethes I can try to take a look later today and make sure there's no other blockers. Been quite busy with other things lately.

**Comment by dpethes** [comment]
Sure, thanks a lot! Let me know if I can help with anything.

**Comment by mellinoe** [comment]
I merged the changes back to master, along with an updated cimgui.so. I need to build cimgui.dylib still, so I haven't published a new NuGet package yet.

**Comment by dpethes** [comment]
Great, thanks!

**Comment by dpethes** [comment]
As you haven't closed this - 1.51 is out and cimgui is already updated. I will have time to make the necessary changes next week (if you haven't started working on it yet).

**Comment by mellinoe** [comment]
@dpethes Sounds good. I am very busy with other stuff at the moment so I'd appreciate any help. I haven't started on 1.51 (didn't know it was out actually).

**Comment by mellinoe** [comment]
I'm going to close this issue out because 1.50 is actually officially supported now that I've updated the OSX binary. I'll file a new issue for 1.51.
