### ISSUE TITLE
Monogame viewport

### ISSUE THREAD

**Issue by NayGames** [mellinoe/ImGui.NET#196]
![imguiappexample](https://user-images.githubusercontent.com/20281417/91910216-e0e83380-ecae-11ea-9707-ebd50584cb84.jpg)
 
I'm cleary new and I would like to know if it is possible to use the vieport of mongame in ImGUI ?
And how ?

**Comment by mellinoe** [comment]
Good question, but I'm not equipped to answer it very well, since I haven't used MonoGame very much, or deeply enough for this kind of scenario. You will have better luck asking over in the MonoGame repo, or in their Discord server.
