### ISSUE TITLE
ImGui with RaylibCS?

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/ImGui.NET#203]
is there a way to use this with raylibcs?
I have tried doing the following..
```cs
using System;
using System.Collections.Generic;
using System.Text;
using ImGuiNET;
using Raylib_cs;

namespace PureEditor
{
    static class Editor
    {
        public static void Run()
        {
            Raylib.InitWindow(640, 480, "Pure Editor");

            while (!Raylib.WindowShouldClose())
            {
                Raylib.BeginDrawing();
                ImGui.NewFrame(); //tried commenting this out
                ImGui.Begin("Window");

                ImGui.End();
                Raylib.EndDrawing();
            }

            Raylib.CloseWindow();
        }
    }
}
```

**Comment by mellinoe** [comment]
I'm not familiar with Raylib, but the integration won't be quite this simple.

ImGui doesn't do any rendering itself. It just gives you textured triangles that you have to render yourself. If you are using Raylib to render your application, then you would need to pass the triangles into it, issue draw calls, etc. yourself. Again, I'm not familiar with Raylib, so I can't give any more specific advice than that. The [example renderer](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs) uses Veldrid to render and shows what steps need to be taken, but it will likely look very different for Raylib.

**Comment by tienery** [comment]
I realise this is very old and apologies in advance to bumping this up... but if you are still looking for a solution, or if anyone else wishes to find a solution for Raylib, this [code](https://gist.github.com/tienery/c146192a51655652d8facae5a8358230) is what I'm using for my project.
