### ISSUE TITLE
ImGui.PushStyleVar with float parameter causes crash.

### ISSUE THREAD

**Issue by baboongd** [mellinoe/ImGui.NET#204]
Using 1.78 docking with unity,
flags like WindowPadding and FramePadding cause crash with a float, while with Vector2 it works as expected.

**Comment by mellinoe** [comment]
This is a case where the native code expects the function to be called in a certain way, e.g. if using ImGuiStyleVar.WindowPadding or FramePadding then you need to pass a 2-float vector. It only validates this with debug assertions, similar to other runtime validity checks. Unfortunately, it's hard to get these same assertions with ImGui.NET, but it is possible if you build a local cimgui.dll in Debug mode and deploy it to your app.
