### ISSUE TITLE
"Issue: Assembly outside lib folder"

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [mellinoe/ImGui.NET#21]
I have been trying to integrate ImGui.NET into a project that I am working on, but when I attempt to build and run the project with ImGui.NET included, I get the series of warnings shown in this picture:

http://i.imgur.com/FCteV0o.png

If I try to run the project, it fails, saying that it can't find that DLL.

I am using Visual Studio Community 2017 on a Windows 10 machine. The version of ImGui.NET that I am using in the project is the latest commit on the master branch. I have tried moving the DLL to several lib folders on various layers of the project, but to no avail.

**Comment by mellinoe** [comment]
Hey @Sage-of-Mirrors , that warning is actually a NuGet bug, it shouldn't cause any problems.

What error do you get when you try to run the sample?

**Comment by Sage-of-Mirrors** [comment]
I was getting the error when trying to run the solution with ImGui.NET as a project that the main project references.

I decided to convert the original Framework project to .NETCore 1.1 again, using the latest codebase, and adding ImGui.NET and other dependencies as NuGet packages. This may fix the issue, but to test that I have to set up ImGui in my project, which may take some time considering I have no idea how to do it, lol.

**Comment by mellinoe** [comment]
> I was getting the error

Sorry -- but what error? The messages you linked originally are just a warning from creating the nuget package. They are also faulty warnings, so it shouldn't cause any problems.

**Comment by Sage-of-Mirrors** [comment]
No, it's my bad. The actual error was in the statement

> If I try to run the project, it fails, saying that it can't find that DLL.

While ImGui was trying to boot up, it would cause an exception saying that it couldn't find cimgui.dll. I assumed the warning and the error were related.

**Comment by Sage-of-Mirrors** [comment]
I'm not sure what the error was, but after doing the re-conversion, I was able to get ImGui.NET working:

![vzi5ztq](https://user-images.githubusercontent.com/6289769/27014514-0952b420-4ec0-11e7-904c-c7d0d22635e2.png)

Thank you for your help! This is very exciting.
