### ISSUE TITLE
can imgui.net with veldrid be used solely for a game engine without having to mess with veldrid?

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/ImGui.NET#210]
Can the veldrid imgui.net implimentation be used solely for a 3d and 2d game engine without having to mess with veldrid?

**Comment by mellinoe** [comment]
The Veldrid integration here is just a barebones renderer for ImGui itself, it doesn't help much with the general-purpose rendering that you'd want for a full game engine. If you are intending to use Veldrid for the game engine, then it makes sense to use the standard integration. However, if you're planning to use some other graphics API, then it makes sense to render ImGui with that graphics API.
