### ISSUE TITLE
ImGui.InputTextWithHint doesn't take a ref string making it unusable.

### ISSUE THREAD

**Issue by NogginBops** [mellinoe/ImGui.NET#215]
```c++
ImGui::InputTextWithHint(const char* label, const char* hint, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data);
```
This function takes a buffer that can be edited in c++, but in c# it looks like this:
```cs
ImGui.InputTextWithHint(string label, string hint, string buf, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, IntPtr user_data);
```
which doesn't allow for getting back the user input, making the function unusable.

**Comment by mellinoe** [comment]
The other InputText overloads are currently handled manually in [this file](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/ImGui.Manual.cs), the "WithHint" variant could also be added to this file and wrapped in a similar way.

**Comment by zaafar** [comment]
This commit fix it? (https://github.com/mellinoe/ImGui.NET/commit/66f1afa9a268c2b70ff9403c570e45c8847e37a4) so close it?

**Comment by mellinoe** [comment]
Yep, should be supported now, and will be included in the next release.
