### ISSUE TITLE
ImGui.CalcTextSize missing arguments

### ISSUE THREAD

**Issue by NogginBops** [mellinoe/ImGui.NET#216]
The function `CalcTextSize` is defined like this in c++:
```c++
ImVec2 ImGui::CalcTextSize(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width);
```
while the C# version just has the first argument
```cs
Vector2 CalcTextSize(string text);
```
The missing arguments are really useful.

**Comment by zaafar** [comment]
The way C# manages strings and pointers to the strings is very different from the way C++ manages them. Basically, there is no 1 to 1 translation of `text_end` (or any _end, _begin) argument. So if you tell me about your use-case (i.e. provide some examples) I might be able to better implement something that resolves your use-case.

**Comment by NogginBops** [comment]
This is how I would expect the overload to look. 
I'm interested in getting at the two last arguments.
```cs
Vector2 CalcTextSize(string text, bool hideTextAfterDoubleHash, float wrapWidth);
```
