### ISSUE TITLE
Generator not working correctly

### ISSUE THREAD

**Issue by MechSlayer** [mellinoe/ImGui.NET#222]
Im trying to generate the docking branch, but I get a lot of errors because of NULL and union in C# code
![image](https://user-images.githubusercontent.com/37446690/101934678-369d7780-3bde-11eb-9c47-1c0010b2e8d5.png)
![image](https://user-images.githubusercontent.com/37446690/101934725-46b55700-3bde-11eb-9c0a-6d4161364ac1.png)

**Comment by mellinoe** [comment]
Might have been a point-in-time issue, the latest version is being generated from the docking branch without a problem.
