### ISSUE TITLE
AccessViolationException error

### ISSUE THREAD

**Issue by Xoverse** [mellinoe/ImGui.NET#225]
Hi, I get a System.AccessViolationException when I launch my test program, I'm using .NET Framework and C#, I downloaded ImGui.NET From NuGet. Here's the code I made:
```cs
using System;
using ImGuiNET;

namespace ImGuiNET_test
{
    class Program
    {
        static void Main(string[] args)
        {
            ImGui.ShowDemoWindow();
        }
    }
}
```

**Comment by bootzin** [comment]
It's not that simple.. ImGui by itself does not have a rendering pipeline, so it doesn't know how to show the demo window on the screen. I recommend taking a look at the [examples](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs) in this repo and on [imgui](https://github.com/ocornut/imgui/tree/master/backends) itself

**Comment by mellinoe** [comment]
Yes, please take a look at the example projects here. ImGui by itself does not render anything, it just provides data for your own renderer to use.
