### ISSUE TITLE
Clear InputText from code

### ISSUE THREAD

**Issue by bootzin** [mellinoe/ImGui.NET#229]
Is it possible to clear InputText? It seems like it stores a local copy of the string, so simply setting the ref string to empty or byte[] to 0 doesn't work.

**Comment by bootzin** [comment]
Found a way to do it. 
I was essentially passing a class variable as the ref string, where instead I should have passed a local variable, and updated the class variable when the local one changed

```C#
string tmp = searchPattern;
if (ImGui.InputTextWithHint("##Search", FontAwesome5.Search + " Search", ref tmp, 512, ImGuiInputTextFlags.AutoSelectAll))
{
    searchPattern = tmp;
}
```

**Comment by differenceclouds** [comment]
The only way I could get this to work was with an empty string check (null check doesn't work):
```
string roomName = CurrentRoom.name;
if (ImGui.InputText("Room Name", ref roomName, 100, ImGuiInputTextFlags.AutoSelectAll)) {
    CurrentRoom.name = roomName != string.Empty ? roomName : " ";
}
```
