### ISSUE TITLE
Unsafe code

### ISSUE THREAD

**Issue by dmitsuki** [mellinoe/ImGui.NET#23]
I just did a quick once over and is there any particular reason there is so much unsafe code in here? 

Most of the functions just look like a raw pointer needs to be changed to a reference. It says there is an effort underway to change the exposed messages to safe code, but is that still planned? Is contribution welcomed?

**Comment by dpethes** [comment]
Sure, if you find methods that don't need to be unsafe, contributions are welcomed.
Although as (c)imgui uses plenty of pointers, my rough guess is that at least 1/3 of the methods will have to use unsafe.

**Comment by mellinoe** [comment]
The intention is that there are two "layers" in ImGui.NET:

* `ImGuiNative` and related native structures: There are direct imports of the native functions, and are unsafe as such. You have to be careful when using this raw layer.
* `ImGui` and related safe structures. These are the "friendly", "safe" versions of the functions, intended to be directly used by application code. Underneath, they call the unsafe functions.

Contributions are certainly welcome. Please open an issue before you submit a PR so we can discuss anything before you spend time on a solution

**Comment by mellinoe** [comment]
I'm going to close this, but feel free to submit new safe wrapper methods if you find yourself writing too much unsafe code.
