### ISSUE TITLE
combobox

### ISSUE THREAD

**Issue by IlkaySolotov** [mellinoe/ImGui.NET#231]
this is my code
```cs
            string[] weapsArr = { "R-301", "R99", "Devotion", "Prowler", "Havoc", "LStar", "Re45", "Alternator" };
            int i = 0;
            ImGui.Combo("Weapon", ref i, weapsArr, 8);
```
obviously wrong, suggestions? (works fine but i cant change selection)

**Comment by bootzin** [comment]
I have an example [here](https://github.com/bootzin/BootEngine/blob/2fae77af312cde8d93b6ef27e0fdc961ebbbabd8/Shoelace/src/Panels/PropertiesPanel.cs#L294), you may want to take a look

**Comment by IlkaySolotov** [comment]
> I have an example [here](https://github.com/bootzin/BootEngine/blob/2fae77af312cde8d93b6ef27e0fdc961ebbbabd8/Shoelace/src/Panels/PropertiesPanel.cs#L294), you may want to take a look

Thanks very useful

**Comment by IlkaySolotov** [comment]
> I have an example [here](https://github.com/bootzin/BootEngine/blob/2fae77af312cde8d93b6ef27e0fdc961ebbbabd8/Shoelace/src/Panels/PropertiesPanel.cs#L294), you may want to take a look

actually im confused from what you're doing here

```cs
bool isSelected = cam.ProjectionType == projType;
```
would u mind explaining?

**Comment by sonoro1234** [comment]
@IlkaySolotov 

`cam.ProjectionType == projType` is an expression returning a boolean (Are they equal or not?) thats is asigned to `isSelected`

**Comment by mellinoe** [comment]
@IlkaySolotov Your code is actually mostly correct, the only problem is you are continuously reassigning `int i = 0;`, so clicking the combo box will do nothing. If you just hoist that variable out somewhere else (a class-level or static variable), then it will probably do what you expect. @bootzin 's suggestion of using `BeginCombo` + `EndCombo` is also very good, it's a much more flexible way to create a combo box and you can avoid allocating an array of options.
