### ISSUE TITLE
Attempted to read or write protected memory

### ISSUE THREAD

**Issue by Down-s** [mellinoe/ImGui.NET#234]
Hello,

I am getting the following error when I try to call `ImGuiNET.ImGui.Begin("Test");`
`An unhandled exception of type 'System.AccessViolationException' occurred in ImGui.NET.dll: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

I'm simply running a static void from my entry point
`public static void Initialize()
{
    ImGuiNET.ImGui.Begin("Test");
    ImGuiNET.ImGui.End();
}`

**Comment by 9and3** [comment]
I actually have the same exact problem! Btw ImGui.NET is an amazing piece of code, thanks! Can't wait to make it run.

**Comment by Vectron** [comment]
you need to setup a context and more stuff for ImGui to work. check the sample project:
https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs

**Comment by mellinoe** [comment]
As Vectron alluded there's quite a bit more setup code that needs to be in place before you can call into ImGui.NET. Take a look at the two example projects in here to see what is necessary. They can also serve as a good starting point for a larger project.
