### ISSUE TITLE
How do I access GetCurrentWindow?

### ISSUE THREAD

**Issue by Thraka** [mellinoe/ImGui.NET#235]
I see `ImGui::GetCurrentWindow` used a lot in various examples on doing some fun custom stuff (like I found code to do a group box control I want to port) but I can't figure out how this is implemented in this library.

Help?

**Comment by Thraka** [comment]
@mellinoe Ping. Are you available to help me understand how this should work? Cheers!

**Comment by Vectron** [comment]
That is an internal method, so it's not mapped by default.

**Comment by Thraka** [comment]
I see. So perhaps all these examples of custom controls on the ImGui repo are people adding things to the source and compiling them in their personal versions?

**Comment by Vectron** [comment]
are those examples in C#?
most examples use the C++ version of ImGui or the c version CImGui.
they both have access to all functions, this is a C# wrapper over CImGui but the internal functions are not mapped, you can build the project yourself to get internal mapping, or you can wirte the mapping yourself with dll import depending on how many you need.

**Comment by Thraka** [comment]
No, the examples are on the core repo, so they're people doing these things in C++. I think that is what I was confused with, the internal mappings. I didn't understand that they were hidden away. Thanks!
