### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by bob382** [mellinoe/ImGui.NET#237]
Just found this and it looks really neat, so I would like to try it out.
However, I saw that the last time ocornut/imgui was pulled was half a year ago, so it's missing tables among other things.

Is this project abandoned?

**Comment by zaafar** [comment]
it's a bit behind i.e. not using ImGui 1.81 but it's not abandoned.
Feel free to create an MR that updates the ImGui to a newer version.

**Comment by bob382** [comment]
That's good to hear. I tried but could not get it to work, cimgui build and generation went fine(i think), but had issues with the generated c# I have no clue how to fix. Since I would be starting a new project tables would be nice to have from the start instead of dealing with the deprecated columns. Will keep an eye on this, but guess I'd be better of going another route for now.

**Comment by sneusse** [comment]
You might want to follow/observe the discussion here:
https://github.com/mellinoe/ImGui.NET/pull/218

There is a branch with a (semi-)recent imgui 1.80 Version + ImPlot waiting for a merge.
Maybe you can start your project using that branch?

**Comment by bob382** [comment]
Thank you for the tip @sneusse, ImPlot would be a very nice thing to have as well.
I can only seem to find a branch targeting imgui 1.79, so no tables yet unfortunately.
I might have missed it?

**Comment by sneusse** [comment]
@bob382 yeah sorry, you're right. I remembered that wrong. I tried to update the implot branch to 1.80 myself but couldn't quite get it done. 😊 

I did't quite get the transformation of the .json files from the cimgui repo (https://github.com/cimgui/cimgui/tree/master/generator/output)

I ended up using the https://github.com/sonoro1234/LuaJIT-ImGui with a KeraLua+NLua Bridge (not sooo happy with that but it works)

**Comment by sonoro1234** [comment]
@sneusse I am surprised because KeraLua+NLua does not seem to support LuaJIT and LuaJIT-ImGui is dependant on LuaJIT ffi.

**Comment by sneusse** [comment]
Yeah I used this branch to start: https://github.com/fastcoding/NLua

**Comment by bob382** [comment]
@sneusse Thanks for trying :) I would love to use  this instead of wpf/winforms as well, seems like a solid replacement for my use.
Rapid UI development, cross-platform on to of that!

**Comment by TillAlex** [comment]
@sneusse #218 was updated to ImGui 1.82 and recent ImPlot. Recent native libraries can be found in the AppVeyor build artifacts of https://github.com/mellinoe/ImGui.NET-nativebuild/pull/3.

**Comment by mellinoe** [comment]
The project is not abandoned by any means. We're now back in sync with imgui v1.82, and @TillAlex has contributed some awesome new bindings for other cimgui-based projects.

**Comment by pixtur** [comment]
Any chance that the nuget version will also get bumped up?
