### ISSUE TITLE
Cant use InputFloat

### ISSUE THREAD

**Issue by BarisUckardes** [mellinoe/ImGui.NET#239]
Cant give input to InputFloat.

Im using like this
`ImGui.InputFloat("Input flt", ref fltRef);`

Also i checked whether my input system is broken

 ```
if(ImGui.IsKeyDown((int)Keys.D0))
{
      RConsoleLog.DropLog("Pressed");
 }
```
Above code outputs `Pressed `when i press `0` on keyboard.

NOTE : i can also clear the input box with `Backspace`

**Comment by mellinoe** [comment]
You are most likely not routing text input properly in your project. I suggest taking a look at how the sample code here handles text input -- InputFloat and other Input* methods work properly in both of these projects.

https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs#L365-L370
https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram.XNA/ImGuiRenderer.cs#L169-L185

**Comment by BarisUckardes** [comment]
Thank you for your reply

This reference you gave me solved my issue
> https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs#L365-L370

**Issue solved.**
