### ISSUE TITLE
Please add Implot, ImGuizmo and ImNode dlls to deps Folder

### ISSUE THREAD

**Issue by alibeirami** [mellinoe/ImGui.NET#246]
Hi,
I've cloned the current master to use ImPlot functionality (which is great news!). There is no Implot demo in Program.cs so I added ImPlot.ShowDemoWindow accordingly. But It complains about missing cimplot.dll. I couldn't find them online. There are some binaries but They have built against an older version of imgui(1.79).

Can you add appropriate dlls (cimplot.dll, .dylib, .so, ...) which is built against current (1.82) version to deps folder?

Great Work BTW.

**Comment by sonoro1234** [comment]
Is https://github.com/mellinoe/ImGui.NET/pull/218#issuecomment-801475327 useful?

**Comment by alibeirami** [comment]
> 
> 
> Is [#218 (comment)](https://github.com/mellinoe/ImGui.NET/pull/218#issuecomment-801475327) useful?

Hi,
That is excellent. after following that comment, I landed on [this](https://github.com/TillAlex/ImGui.NET-nativebuild/tree/additional_libraries) which I was able to compile and get the files I want. I think adding dlls would be nice though.

Thank you. Your work on these c-bindings are legendary.
