### ISSUE TITLE
Random access violations while using imgui

### ISSUE THREAD

**Issue by ossyahya60** [mellinoe/ImGui.NET#252]
Hi Folks!, I integrated ImGui to my game engine, since then, I get  a lot of (Random access violations, Corrupted memory and others), Iam using version 1.78, do you have any solution for this?

Note:
1- These exceptions happen randomly.
2- These exceptions often happen in 'Sharp.DX'.
3- Iam using Monogame 3.8.

Thanks!

**Comment by julcreutz** [comment]
Hey, so I've analyzed a few crash dumps of mine and found something.

I'm not an expert, but I suppose the most notable lines are these right here:

```
cimgui!igValueInt+0x1f279

ntdll!RtlFreeHeap+0x51
```

I've appended the full crash dump analysis.

[windbg_crashdump_analysis.txt](https://github.com/mellinoe/ImGui.NET/files/6334895/windbg_crashdump_analysis.txt)

**Comment by ossyahya60** [comment]
@mellinoe  Hi,  I know you are a busy person, but can you look into this issue?

**Comment by ossyahya60** [comment]
I solved the issue, it was related to the ID stack, I was popping IDs without pushing (Fatal mistake).
All thanks to @julcreutz  in Issue number #251
