### ISSUE TITLE
Colored Words

### ISSUE THREAD

**Issue by Pastor111** [mellinoe/ImGui.NET#262]
Is there a way to change the color of a specific word in a text?

**Comment by SMACheats** [comment]
ye 						ImGui.TextColored(new Vector4(0.0f, 1.0f, 0.24f, 1.0f), "Your Text"); // Green

**Comment by richardlalancette** [comment]
Guys, please look into the API before asking such trivial questions LOL

**Comment by mellinoe** [comment]
@SMACheats provided the closest feature here. As far as I know, there's no way to do "rich text" markup a la Unity's gui, e.g. `ImGui.Text("hello <color=red>world</color>");`. See this issue: https://github.com/ocornut/imgui/issues/902. So your best bet is to use Text+TextColored and SameLine.

**Comment by FortKid** [comment]
**FIX FOUND**
```
        public static void ImGuiColorText(String Text, Color color)
        {
            ImGui.TextColored(ColorToVector4(color), Text);
        }

        private static Vector4 ColorToVector4(Color Color)
        {
            return new Vector4((float)Color.R / 255.0f, (float)Color.G / 255.0f, (float)Color.B / 255.0f, (float)Color.A / 255.0f);
        }
```

**Comment by guillaC** [comment]
> id ImGuiColorText(String Text, Color color)
>         {
>             ImGui.TextColored(ColorToVector4(color), Text);
>         }
> 
>         private static Vector4 ColorToVector4(Color Color)
>         {
>             return new Vector4((f

You can also simply cast like this:
`ImGui.TextColored((Vector4)Color.Violet, "Hey");`
