### ISSUE TITLE
ImGuizmo.NET asking for ref float where it should be asking for a matrix

### ISSUE THREAD

**Issue by FloatingBanana** [mellinoe/ImGui.NET#266]
Some function arguments like `view` and `projection` should be a 4x4 matrix or at least a `float[16]`, but instead they'r just asking for a `ref float`.  Here's an [example](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGuizmo.NET/Generated/ImGuizmo.gen.cs#L82)

**Comment by zaafar** [comment]
if u create float[16] then pass in "ref float[0]", it will work.

**Comment by FloatingBanana** [comment]
Thanks, I would never guess it was like this
