### ISSUE TITLE
IO.MousePosition goes negative when leaving window bounds

### ISSUE THREAD

**Issue by bennybroseph** [mellinoe/ImGui.NET#27]
Small thing with the sample window.

https://github.com/mellinoe/ImGui.NET/blob/6b2c655922cee66dbb3938a1cd94b0f169d7966d/src/ImGui.NET.SampleProgram/SampleWindow.cs#L322

Should read as 
```csharp
if (_nativeWindow.Focused)
```
I know that file probably hasn't been touched in quite some time, but for myself and probably others, the code in that file is what we use to quickly get ImGui initialized without having to write a bunch of translated code. Figured I'd help fix that small annoyance.

For those wondering, this is what makes the values on a DragFloat or similar widget go negative when leaving the window. In all the imgui c++ examples, you are supposed to check to see if the window is focused, so I did the same here instead of seeing if the mouse is contained in the current context.

**Comment by mellinoe** [comment]
Ah, that is probably a good change. I'm actually on vacation right now away from my main computer, so I probably won't fix the example code for a little while. Feel free to submit a fix if you'd like!

Cheers

**Comment by mellinoe** [comment]
Looks like this is fixed now.
