### ISSUE TITLE
How do I include ImGui.Net Source code into my own project?

### ISSUE THREAD

**Issue by Pandaroses** [mellinoe/ImGui.NET#275]
Im trying to add ImGui.Net as a seperate source project in my solution however i see like 7 csproj's and im not sure which ones to include in my solution.

**Comment by mellinoe** [comment]
You just need ImGui.NET. The others are:

* CodeGenerator (not needed at runtime)
* Example projects
* Auxiliary libs (you could include these if you wanted more features)
