### ISSUE TITLE
text input doesn't work

### ISSUE THREAD

**Issue by makarhuyaker** [mellinoe/ImGui.NET#280]
i actually fork imguiCS but when i rewrote everything under imgui.net it didn't help so how do i get the text input to work?

**Comment by zaafar** [comment]
@makarhuyaker check the example projects provided in this repository. Input text works there.

**Comment by makarhuyaker** [comment]
> @makarhuyaker check the example projects provided in this repository. Input text works there.

uh ...... so this is the problem I have an application in which I embed imgui and it looks like it intercepts keystrokes

**Comment by zaafar** [comment]
sounds like an issue in your application and how it intercepts keystrokes rather than ImGui/ImGui.NET issue.

**Comment by makarhuyaker** [comment]
I already understood

**Comment by makarhuyaker** [comment]
I found out that this is most likely not a problem of my application, I am most likely not using input correctly, can you give a working code of the inputtext? i use private byte [] buff = new byte [10]

**Comment by makarhuyaker** [comment]
@zaafar

**Comment by zaafar** [comment]
create a class level string as show below.

private string displayName = string.Empty;

then use it in the InputText as shown below.

ImGui.InputText("Display Name", ref this.displayName, 50);

**Comment by makarhuyaker** [comment]
what about the textinputbuffer class? i tried to use it like in sdl2 example but got AccessViolationException

**Comment by makarhuyaker** [comment]
> ref this.displayName

argument 2 should not be passed with the ref keyword

**Comment by makarhuyaker** [comment]
forgot to say i'm using a fork of imgui.net imguics but wrote it here because the repository is zipped but when i tried to use imgui.net the text input also failed

**Comment by zaafar** [comment]
> forgot to say i'm using a fork of imgui.net imguics but wrote it here because the repository is zipped but when i tried to use imgui.net the text input also failed

https://github.com/0x0ade/ImGuiCS/blob/master/ImGuiSDL2CS-Example/src/YourGameWindow.cs#L67

That library was last updated in 2018. I would suggest you to use this lib rather than that one.

**Comment by makarhuyaker** [comment]
I already said that I tried to use the textinputbuffer class but got an AccessViolationException and about the second one, the fact is that I already wrote quite a lot of code and I just don't want to port it to imgui.net

**Comment by zaafar** [comment]
> I already said that I tried to use the textinputbuffer class but got an AccessViolationException and about the second one, the fact is that I already wrote quite a lot of code and I just don't want to port it to imgui.net

hmm, no idea in that case. What I would suggest is to clone that repository and see if examples are working over there. If yes, try to figure out what that repo example is doing that you aren't.

**Comment by makarhuyaker** [comment]
just now i created an empty xna project and checked the text input there and it doesn't work either all the same it's a problem imgui

**Comment by makarhuyaker** [comment]
now I will try with imgui.net

**Comment by makarhuyaker** [comment]
doesn't work either

**Comment by zaafar** [comment]
yeah that repository/library is very old so make sense.
However, this repository/library has no connection with that repository/library.

**Comment by makarhuyaker** [comment]
yes I know but let's say I redid the code for imgui.net but my text input still won't work

**Comment by makarhuyaker** [comment]
maybe the problem is in the cimgui which I am using tomorrow I will try a new version

**Comment by mellinoe** [comment]
Without any code, this isn't an actionable issue. As stated above, the example project in this repository details exactly how to get input working. If you're using a different window/input system (or an entirely different set of bindings to dear imgui...), then I suggest you open an issue against the other library that you're using.

**Comment by makarhuyaker** [comment]
it really doesn't work with xna

**Comment by makarhuyaker** [comment]
I will upload my project to github
