### ISSUE TITLE
BeginMenuBar not working in MonoGame

### ISSUE THREAD

**Issue by bangclash** [mellinoe/ImGui.NET#281]
I'm trying to draw a menu in a window and it doesn't work. All I see is the button. See below for code and screenshot. Any help is greatly appreciated.

            imGuiRenderer.BeforeLayout(gameTime);

            if (ImGui.Begin("First"))
            {
                if (ImGui.BeginMenuBar())
                {
                    if (ImGui.BeginMenu("File"))
                    {
                        if (ImGui.MenuItem("New"))
                        {
                        }
                        ImGui.EndMenu();
                    }
                    ImGui.EndMenuBar();
                }
                if (ImGui.Button("Test"))
                    Console.WriteLine("Click");
                ImGui.End();
            }
            imGuiRenderer.AfterLayout();

![imgui](https://user-images.githubusercontent.com/10566143/141924884-c5b4216e-845e-463c-bf28-643eb69d731a.jpg)

**Comment by zaafar** [comment]
Pass ImGuiWindowFlags.MenuBar to the begin function.

**Comment by bangclash** [comment]
Thank you for the quick response, that worked! Is this expected behavior? All the samples I saw online did not have that flag.

**Comment by zaafar** [comment]
no idea, it works for me, so i am good.
