### ISSUE TITLE
Support PushItemFlags

### ISSUE THREAD

**Issue by ZhiruiLi** [mellinoe/ImGui.NET#282]
This function is important for disable/enable GUI items, but it seems that it is not appear in interface.

For more information about this function, see [ocornut/imgui #1889](https://github.com/ocornut/imgui/issues/1889).

**Comment by mellinoe** [comment]
This is another case where we need access to internal functions: #81

**Comment by Thraka** [comment]
I just ran into needing this so that I can disable a button in the generated UI.

**Comment by Vivian-A** [comment]
@zaafar 
I'm aware of these functions. I need access to imgui_internal.h.

**Comment by zaafar** [comment]
Oh my bad! I read your comment incorrectly. :) yeah, I don't think so there is any progress ( or anyone working ) on adding internal functions.


Although I did notice a new repo for porting ImGui to C# today, you may wanna explore that as well.

**Comment by mellinoe** [comment]
`ImGui.BeginDisabled` and ImGui.`EndDisabled` have been available for some time now, and are not part of the internal API. I'm going to close this out since the original request was to access that functionality, which is now available. #81 is still relevant for other internal things.
