### ISSUE TITLE
Using object properties with InputText

### ISSUE THREAD

**Issue by bangclash** [mellinoe/ImGui.NET#284]
I know I can pass a string variable as ref to an InputText. I cannot pass an object property as ref to InputText. What I do now is just assign a string variable to the object property and then pass that string variable to the InputText. This works but then I have to reassign that string variable back to the object property when there is a change. Is there a better technique that I can use? I'm very new to ImGui.

**Comment by zaafar** [comment]
That’s the only way as far as I know. Normally I do not create properties if I know something is gonna be used in ImGui.

**Comment by bangclash** [comment]
@zaafar I come from xmal and winform so I'm still use to object binding. This immediate mode gui is new to me. I was hoping there is some magic technique that someone can tell me about.

**Comment by mellinoe** [comment]
I'd suggest creating a wrapper function if you want to pass a non-string object to the InputText function. Then, you only need to implement the reassignment logic once.
