### ISSUE TITLE
How to create a project

### ISSUE THREAD

**Issue by W0lfDev** [mellinoe/ImGui.NET#285]
Hi!

I really liked the idea about Dear ImGUI with c#
I just cant understand how to create a project inside visual studio 2022 and how to download the package.

Can someone help me please

**Comment by SecuritySlayer** [comment]
> 

I have the same issue

**Comment by mellinoe** [comment]
ImGui.NET is on NuGet: https://www.nuget.org/packages/ImGui.NET/. If you're using VS, then you can use some built-in menus to install packages into your project: https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio. ImGui.NET by itself doesn't provide a renderer, I'd suggest installing the basic Veldrid packages (Veldrid.ImGui, Veldrid.StartupUtilities) as well to get a simple renderer working. Forking the example project in this repository is actually the easiest way to get yourself bootstrapped.
