### ISSUE TITLE
Buttons with image?

### ISSUE THREAD

**Issue by makarhuyaker** [mellinoe/ImGui.NET#286]
I have if I'm not mistaken (maybe I'm wrong now there is no access to the pc to check) xna texture2d and I want to display this texture on a button I just need a code I have no idea about the format of textures imgui.net / imgui

**Comment by makarhuyaker** [comment]
for some reason i cant display the texture instead of white square i use https://github.com/0x0ade/ImGuiCS/blob/master/ImGuiFNA/src/ImGuiXNAState.cs

**Comment by makarhuyaker** [comment]
already done (I used new ImGuiXNAState when the state already existed and it was a black / white square)

**Comment by mellinoe** [comment]
I can't provide support for another ImGui-based library. If you try to use this library (ImGui.NET) and have a specific question, preferably with a more complete description of what you've tried and why it didn't work, then feel free to open a new issue.
