### ISSUE TITLE
Inverted Window?? WTF?

### ISSUE THREAD

**Issue by wh0am15533** [mellinoe/ImGui.NET#287]
I'm using the latest master v1.82 in a project for Unity, although I don't use a Unity Project it's in a mod for at runtime that injects ImGui into a game. I finally got everything to work the only thing is that the ImGui window is upside down. (DirectX11) Is there some way to flip it?

**Comment by mellinoe** [comment]
It's really hard to say what is going wrong without any of the relevant code here. My guess is that there's a mismatch between coordinate system conventions somewhere in the rendering path here. The easiest place to fix it is probably in the ImDrawList/ImDrawData renderer.

**Comment by wh0am15533** [comment]
Yeah it's the projection matrix, I figured it out, but I wish I could detect if the window is upside down or not. I inject into a Unity Game Runtime, and on some system's using DirectX11 it's fine, on other's using DirectX11 still, it's inverted. Right now I'm fixing it with flipping the matrix with hotkey, but then the scissor's clipping doesn't work right. I'm getting closer. Thnx for help, and the new update!

**Comment by mellinoe** [comment]
You could probably use one of these macros to detect whether the output should be inverted in your shader: https://docs.unity3d.com/Manual/SL-BuiltinMacros.html. Specifically, the `UNITY_UV_STARTS_AT_TOP` macro sounds like it would be helpful. That way, you could solve it in one place. I'll go ahead and close this issue unless there's something to fix in ImGui.NET, but it sounds like there's not. Cheers!
