### ISSUE TITLE
Suggestion: add an opengl example

### ISSUE THREAD

**Issue by JamesC01** [mellinoe/ImGui.NET#290]
I've been learning opengl recently, using opentk, and really wanted a simple gui to tweak with values at runtime, but I just can't find anything. I've tried implementing my own imgui.net renderer by looking at the current samples and the imgui c++ backends, but I just can't understand it. An opentk or silk.net example would be really nice, just a very minimal one. Sorry if this sounds demanding, I just thought it would be quite nice.

**Comment by djgaven588** [comment]
This already exists: https://github.com/NogginBops/ImGui.NET_OpenTK_Sample
One of the maintainers of the OpenTK project made this example, it sadly doesn't support multiple viewports and such, however it will get you started.

It would be great if more examples were in this project, however it seems others have made their own.

**Comment by JamesC01** [comment]
> This already exists: https://github.com/NogginBops/ImGui.NET_OpenTK_Sample One of the maintainers of the OpenTK project made this example, it sadly doesn't support multiple viewports and such, however it will get you started.
> 
> It would be great if more examples were in this project, however it seems others have made their own.

Thanks!

**Comment by mellinoe** [comment]
Looks like the example above is sufficient. I'm not opposed to including one here if it's built on top of a well-supported OpenGL wrapper, and ideally which shares code with the existing example projects.
