### ISSUE TITLE
upgraded nuget to 1.87.2 in my monogame project and now I get errors.

### ISSUE THREAD

**Issue by bangclash** [mellinoe/ImGui.NET#299]
I have a monogame 3.8 project. Upgrade the imgui nuget package from 1.86 to 1.87.2. If I revert back to 1.86 everything is fine.

I get this warning message below:
Warning	NU1701	Package 'ImGui.NET 1.87.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.	

Build now fails with error below:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'ImGui' does not exist in the current context

**Comment by Vectron** [comment]
it's probably because the latest package targets NET6.0, this means anything below net6.0 might get errors,
your project targets NET Core 3.1.
if you upgrade your project to NET6 it will probably work with the latest version

**Comment by bangclash** [comment]
I really hope that is not the case.

**Comment by mellinoe** [comment]
Please try this again with 1.87.3, we've added back the previous framework targets so backwards compatibility should be restored.

**Comment by bangclash** [comment]
1.87.3 is now working with MonoGame 3.8, thank you.
