### ISSUE TITLE
Mouse pressing not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by feliwir** [mellinoe/ImGui.NET#3]
Hello, i am compiling the sample window on Ubuntu 16.04, but when pressing my mouse i get no feedback (e.g. slider not working, pressed label remains false)

**Comment by mellinoe** [comment]
I don't have an Ubuntu 16.04 machine set up right now, but I have tested extensively on 15.04, so I don't think there should be a big difference between the two.

Could you try to debug the messages coming from the window for me? For example, print out the mouse position and mouse button states from the `UpdateImGuiInput` and see if it matches up with what you're actually doing? I'm wondering if the windowing/input support from OpenTK has any issues in this area.

**Comment by feliwir** [comment]
UpdateImGuiInput is all correct (it recognized mousedown etc.), but when reading out of ImGui.GetIO().MouseDown[0]; in SubmitImGuiStuff() it is always not pressed. But the code looks correct to me i don't understand why it keeps being false

**Comment by mellinoe** [comment]
Hmm, interesting. I will try to re-purpose one of my old laptops later and see if I can install Ubuntu 16.04 on it and get a repro.

Is the mouse position being correctly updated in imgui? It would be obvious if it worked correctly, since the buttons, etc. would light up as you hovered them. Does directly setting the value in the native structure, i.e. `ImGuiNative.igGetIO()->MouseDown[0] = 1;` have any effect for you?

**Comment by mellinoe** [comment]
I set up my machine with Ubuntu 16.04 and I'm not able to reproduce the issue :disappointed: . Are you running the sample using CoreCLR, or mono?

**Comment by feliwir** [comment]
I am using CoreCLR together with the Visual Code plugin. The mouse position is updated correctly i'll try to set mousedown later manually

**Comment by mellinoe** [comment]
@feliwir Did you ever get a chance to try this out some more? Like I said, I wasn't able to reproduce this on my end. Let me know if you have more info!

**Comment by mellinoe** [comment]
I'm not able to repro this and I can't help without a bit more information. If you end up trying this out again, feel free to re-open and I will try to investigate more.
