### ISSUE TITLE
Sample Program's Window Loop should use SpinWait instead of Sleep

### ISSUE THREAD

**Issue by ErenForce** [mellinoe/ImGui.NET#30]
Spinning using `Sleep(0)` will pin the working core and be disastrous on single core machines. Using `SpinWait.SpinUntil` will insure that the spinning will include thread yields and occasional sleeps to prevent starving other threads.

**Comment by mellinoe** [comment]
Hey @ErenForce, I'm certainly open to improvements to the sample code. I haven't spent a ton of time on little improvements like that -- it's mostly there to show some basic integration and demonstrate how the library can be used.

> Sleep(0) will pin the working core and be disastrous on single core machines

I'd like to understand what this means a bit more. We could switch to `SpinWait`, although it's not really semantically the same. If we updated the target framework of the sample, we could also use `Thread.Yield`, which seems appropriate.

**Comment by ErenForce** [comment]
Looping with sleep like that will consume all of the CPU cycles. Right now on my machine, running the program keeps my cpu usage at a steady 25% (I have four cores). Switching to SpinUntil removes the usage while keeping the app responsive.
Also SpinWait mostly uses `Thread.Yield` internally after it's done at least 10 iterations and it shortens code from the while loop to simply `SpinWait.SpinUntil(() => DateTime.UtcNow > finishTime);`... and it's available with netcore1.0. It seems like a good choice to me.

**Comment by mellinoe** [comment]
From what I understand, `Sleep(0)` should yield to other threads, provided there are any waiting. I'd be happy to take a PR that changes the behavior, though, if it's strictly better.

**Comment by ErenForce** [comment]
`Sleep(0)` is very very weird. Give this a skim, [Priority-induced starvation](http://joeduffyblog.com/2006/08/22/priorityinduced-starvation-why-sleep1-is-better-than-sleep0-and-the-windows-balance-set-manager/). All that boilerplate code is shoved into [SpinOnce()](https://referencesource.microsoft.com/#mscorlib/system/threading/SpinWait.cs,120) with additional logic for using the CLR's SpinWait for waits that use less than 10 iterations (which is what probably fixes the high CPU usage).

**Comment by stakira** [comment]
Sleep(0) utilize a core to 100% on my windows, Sleep(1) bring it down to 3%.

**Comment by wirmachenbunt** [comment]
hi, any progress here, i just found this neat GUI lib but noticed a heavy cpu difference between this wrapper and the original c++ demos. its like 2% (c++) vs. 25% hence one core of four with this .net wrapper

**Comment by mellinoe** [comment]
I've overhauled the sample project entirely as of https://github.com/mellinoe/ImGui.NET/commit/ebb5fe2c6171db172612d1f7d65d6c747055c85b. The new code simply waits on vsync of the application's main swapchain, so I don't think there's much to improve here.
