### ISSUE TITLE
Trying to make a version that support XNA 4

### ISSUE THREAD

**Issue by RedDude** [mellinoe/ImGui.NET#303]
Hi, I'm trying to make a version that support .net 45, which is the last version to XNA 4 (at least for the game that I'm modding)

I did replace all the System.Numerics Vectors to the XNA vectors. and I had to target to x84, since the XNA from the game uses it.
I also did change some Buffer.MemoryCopy to Unsafe.CopyBlock.

I manage to build both Imgui.net and the XNA sample. however I'm getting the following error:

nhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at ImGuiNET.ImGuiNative.igCreateContext(ImFontAtlas* shared_font_atlas)
   at ImGuiNET.ImGui.CreateContext()
   at ImGuiNET.SampleProgram.XNA.ImGuiRenderer..ctor(Game game)
   at ImGuiNET.SampleProgram.XNA.SampleGame.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at ImGuiNET.SampleProgram.XNA.Program.Main(String[] args)

 
I'm not any specialist with wrapper's and bindings for C libraries. This is the first time ever that I try to do something similar.
I have to adjust the generator to fit some vector size difference between the XNA version or something like that?

I did try to follow any tips on the #17 , and checking @dpethes had a .Net 4.0 fork like he said, however I did not find it or had any success which that. 
Any directions that could help me to getting it running would be much appreciate 

Thank you so much

**Comment by CEO-Chair** [comment]
This is not a problem with Dear ImGui or ImGui.NET or the other managed assemblies, but you are simply using the wrong architecture of cimgui.dll.

**Comment by RedDude** [comment]
I'm sure that there is nothing wrong with Dear ImGui or ImGui.NET, they work perfectly fine. However, there are something definitely wrong with me. I'm just struggling to get it working and the "issues" were the only place where I found to get some help.

So, also need to build a different cimgui for .net 45? I'm referencing the cimgui.dll from "/deps/cimgui/win-x86/" in both ImGui.NET and the XNA sample. Thought that ones that comes with ImGui.NET would do the tricky, since the my project and cimgui are both targeting win-x86.

Sorry for being a newbie and I'm totally aware how spend time helping clueless people is not great. However, I'm humbling asking for directions to get it working.

**Comment by mellinoe** [comment]
Almost every time that you see that specific exception ("An attempt was made to load a program with an incorrect format"), it means that you're trying to load a native library for the wrong architecture. I would suggest you load this up under a debugger to confirm exactly:

* Which architecture your program is running with at runtime (regardless of how it's configured). Is it 32- or 64-bit?
* Which cimgui.dll file is being loaded and what architecture it is compiled for.

**Comment by mellinoe** [comment]
Please reopen if you're able to provide more info or if the above didn't resolve it for you.
