### ISSUE TITLE
Problems with Monogame and ImGUI

### ISSUE THREAD

**Issue by BreyTheKid** [mellinoe/ImGui.NET#306]
I have two problems, neither of which I'm sure how to solve. I have attached my project folder. First, adding a custom font does not seem to be working. I have a line commented out as it causes an error. Second, for whatever reason, all text seems to be clipped a few pixels at the top. Any idea how to fix either of these? Thanks!

Project download: 
[https://filebin.net/ljq6ixdvl5llwj4q](url)

**Comment by Cuber01** [comment]
See:
https://github.com/mellinoe/ImGui.NET/issues/162
https://github.com/mellinoe/ImGui.NET/issues/132

**Comment by mellinoe** [comment]
I'd suggest raising this in a Monogame-specific support forum. There's most likely some issues with how the renderer is configured in your project, but I'm not terribly familiar with the library to help on that level. My only suggestion would be to compare/contrast the example project in this repository to see if it helps identify the problem.
