### ISSUE TITLE
ImPlot binary

### ISSUE THREAD

**Issue by mbwilding** [mellinoe/ImGui.NET#310]
Anyone able to give me the ImPlot binaries, tried compiling and always getting:

System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

when it hit this in ImPlot.gen.cs:
byte ret = ImPlotNative.ImPlot_BeginPlot(native_title_id, native_x_label, native_y_label, size, flags, x_flags, y_flags, y2_flags, y3_flags, native_y2_label, native_y3_label);

I have built the latest binaries, got the latest cimgui.dll and cimplot.dll but I get this error.
cimgui.dll works fine when not using ImPlot.

**Comment by SupreethaJayaram** [comment]
@mbwilding  have you overcome this issue ?

**Comment by Stars-6195** [comment]
okay thank you 👍
