### ISSUE TITLE
I still need cimgui.dll

### ISSUE THREAD

**Issue by mavmarong** [mellinoe/ImGui.NET#315]
I still need to put cimgui.dll in the same folder of my ImGui.NET program, how can I fix this or like merge the dll into the program?

**Comment by zaafar** [comment]
did you import the imgui.net from nuget package manager?

**Comment by mavmarong** [comment]
> did you import the imgui.net from nuget package manager? is the cimguii.dll available in the runtime folder?

yes, is that the problem?

**Comment by mavmarong** [comment]
> did you import the imgui.net from nuget package manager? is the cimguii.dll available in the runtime folder?

it is. My problem is that i dont want to put everytime the dll in the folder of my application, how can i fix it and maybe like merge the dll?

**Comment by Vectron** [comment]
If you are targeting net framework there are problems with finding the dll in the runtime folder.
Same problem if you have a project reference to ImGui.Net

In these cases it's best to use a post build script to copy the dll next to your exe.
