### ISSUE TITLE
Automatic texture binding

### ISSUE THREAD

**Issue by dclipca** [mellinoe/ImGui.NET#320]
I'm wondering if it would make sense to make some kind of system that would cache `Texture2D`s. Maybe a dictionary of `Texture2D` to `IntPtr`. Would that make sense?

https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram.XNA/SampleGame.cs

```
// Texture loading example

			// First, load the texture as a Texture2D (can also be done using the XNA/FNA content pipeline)
			_xnaTexture = CreateTexture(GraphicsDevice, 300, 150, pixel =>
			{
				var red = (pixel % 300) / 2;
				return new Color(red, 1, 1);
			});

			// Then, bind it to an ImGui-friendly pointer, that we can use during regular ImGui.** calls (see below)
			_imGuiTexture = _imGuiRenderer.BindTexture(_xnaTexture);
```

**Comment by dclipca** [comment]
Relating to problems people had (including me) with binding at every frame.

https://github.com/mellinoe/ImGui.NET/issues/183
https://github.com/mellinoe/ImGui.NET/issues/92

**Comment by mellinoe** [comment]
The Veldrid renderer has a really basic cache implemented, feel free to take inspiration from here: https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram/ImGuiController.cs#L138-L155
