### ISSUE TITLE
Fullscreen borderless transparent

### ISSUE THREAD

**Issue by mbwilding** [mellinoe/ImGui.NET#331]
Wanting to make a full screen overlay, I've removed all the window stylings and have it full screen but cannot make it transparent so I can draw on top of it to seem like there isn't a window. Anyone have an example?

**Comment by zaafar** [comment]
@mbwilding try https://github.com/zaafar/ClickableTransparentOverlay

**Comment by mbwilding** [comment]
I found your thing last night hence closing my ticket, you're a legend!
