### ISSUE TITLE
What color format imgui uses?

### ISSUE THREAD

**Issue by iocmet** [mellinoe/ImGui.NET#333]
(sorry i posting that in this repo i can't post it to official imgui repo it says You can't perform this action at that time)
In imgui demo i see following code lines
`            if (strstr(item, "[error]"))          { color = ImVec4(1.0f, 0.4f, 0.4f, 1.0f); has_color = true; }
            else if (strncmp(item, "# ", 2) == 0) { color = ImVec4(1.0f, 0.8f, 0.6f, 1.0f); has_color = true; }
            if (has_color)
                ImGui::PushStyleColor(ImGuiCol_Text, color);`
but what color format is it? it not rgba or cmyk i dont have any ideas

**Comment by mellinoe** [comment]
Colors are stored in a 4-element vector, where each element is a 32-bit float encoding a normalized color value (e.g. the values span from 0.0 to 1.0). RGBA order.
