### ISSUE TITLE
Add support for the Dock Builder.

### ISSUE THREAD

**Issue by ohtrobinson** [mellinoe/ImGui.NET#336]
Support for the dock builder appears to be missing.

A couple of enums seems to have made it in but apart from that support seems to be entirely missing.

Any chance we could see support for the dock builder at some point soon?

**Comment by mellinoe** [comment]
The DockBuilder API is still in the "internal" part of the native library (imgui_internal.h). I'm going to close this isuse and keep tracking it over in #81 since this isn't specific to the DockBuilder.

**Comment by clibequilibrium** [comment]
@ohtrobinson  you can use this [fork](https://github.com/equilibrium-hub/ImGui.NET) to generate DockerBuilder or use the packaged NuGet directly. I don't guarantee 100% support or uptime of it.

`<PackageReference Include="ImGui.SDL.Dockspace.NET " Version="1.89.1" />`

```CSharp  
                    ImGui.DockBuilderRemoveNode(dockspaceId);
                    ImGui.DockBuilderAddNode(dockspaceId, (ImGuiDockNodeFlags)((int)dockspaceFlags | 1 << 10));
                    ImGui.DockBuilderSetNodeSize(dockspaceId, viewport.Size);

                    uint dock_id_left =
                        ImGui.DockBuilderSplitNode(dockspaceId, ImGuiDir.Left, 0.2f, out var _, out dockspaceId);
                    uint dock_id_down =
                        ImGui.DockBuilderSplitNode(dockspaceId, ImGuiDir.Down, 0.25f, out var _, out dockspaceId);
                    uint dock_id_up =
                        ImGui.DockBuilderSplitNode(dockspaceId, ImGuiDir.Up, 0.55f, out var _, out dockspaceId);

                    uint right;
                    uint left;

                    ImGui.DockBuilderSplitNode(dock_id_up, ImGuiDir.Right, 0.55f, out right, out left);
                    ImGui.DockBuilderFinish(dockspaceId);
```

This code splits the dockspace in 4 parts as an example:


![image](https://user-images.githubusercontent.com/105135724/213882686-f6b01a20-ea76-420f-9e18-c96843454444.png)
