### ISSUE TITLE
Support of "docking" branch on NuGet

### ISSUE THREAD

**Issue by mrpierrot** [mellinoe/ImGui.NET#339]
Like the [previous issue](https://github.com/mellinoe/ImGui.NET/issues/336), I'am interessing too for a docking support on NuGet. (https://www.nuget.org/packages/ImGui.NET/1.87.3)
(If you consider this issus is a duplicate of the previous, we can merge it, sorry) 

I see this repo have a "docking" branch but not a package built with it. 
I can build a proper package with docking version. But I don't think it's durable solution. 

Do you think we can have a kind of "1.87.3-docking" version on NuGet ?

Thank you very much.

**Comment by mellinoe** [comment]
Hey @mrpierrot, there's actually no difference in the native bindings between the two branches here in this repository. The master branch (which the NuGet package is generated from) is already using the docking branch of the native library, and exposes all of the necessary functionality in it.

The only difference in the `docking` branch here is that the example project uses multi-viewports.

**Comment by mrpierrot** [comment]
Okay. Sorry I would try to use the multi viewport and I don't succeeded.. And I think that can be due to a "no support" of the docking branch. 
But I 'am happy to know there is a example for Multi Viewport. But the Xna example is not updated with the multiviewport.
Can that be possible to use MultiViewport with Monogame ? That imply create multiple windows that write ?  (Monogame documentation/articles not seems very exhaustive on this subject.
Thank you.
