### ISSUE TITLE
Unable to load DLL 'cimgui' or one of its dependencies when using Docking branch

### ISSUE THREAD

**Issue by ScottKane** [mellinoe/ImGui.NET#344]
I'm trying to use the docking branch with a Silk.NET Vulkan sample updated to .NET 6.0 (https://github.com/ScottKane/ImGuiVulkan). Using the normal ImGui.NET package everything works fine, however when I try to switch to the docking branch, I get a DLL exception `Unable to load DLL 'cimgui' or one of its dependencies`.

When running on master branch I get the following in the build output directory:
![image](https://user-images.githubusercontent.com/17254944/182974856-7622a48a-91c7-45c9-9506-0e028ed2941c.png)

And when running with the docking branch I get:
![image](https://user-images.githubusercontent.com/17254944/182974911-5ade5b1d-a8ec-4a94-8434-528b85ec9f84.png)

As you can see, `cimgui.dll` is present in both and judging by the size differences everything looks fine. Any ideas what might be going on here?

Running .NET 6.0 on Windows 11 64 bit

**Comment by nathan130200** [comment]
#296 Same problem on linux.
