### ISSUE TITLE
Are hardware cursors supported?

### ISSUE THREAD

**Issue by aybe** [mellinoe/ImGui.NET#354]
I am using your library through OpenTK, currently I can only see an arrow cursor.

Try to understand what's causing this, does ImGui.NET supports mouse cursors?

Thank you.

**Comment by zaafar** [comment]
not really related to OpenTK but here is how I am showing different cursors in dx11 & Win32 & imgui. Hopes it helps...

https://github.com/zaafar/ClickableTransparentOverlay/blob/master/ClickableTransparentOverlay/ImGuiInputHandler.cs#L23

https://github.com/zaafar/ClickableTransparentOverlay/blob/master/ClickableTransparentOverlay/ImGuiInputHandler.cs#L86

**Comment by aybe** [comment]
@zaafar 

This is at the same time great and not so great, I had to rewrite a substantial portion of what GLFW, OpenTK and Win32 already do, so I tried that, until things broke and aren't seen anymore by OpenTK and the thing started acting weird. 

In your case it's okay since you're bare metal, there's no intermediate layer and you have full control of things.

Thanks anyway 😀

**Comment by aybe** [comment]
Problem solved, solution: https://github.com/ocornut/imgui/issues/5739#issuecomment-1268734162
