### ISSUE TITLE
Version of 1.88 was released in 21.06.22 - Will This imGUI be updated to that version at some point?

### ISSUE THREAD

**Issue by Shpendicus** [mellinoe/ImGui.NET#356]
Title. Would just be cool to see that this beautiful lib in C# is being updated frequently :) 

Much love.

Cheers.

**Comment by zaafar** [comment]
it's almost time for 1.89. should wait for that. :)

**Comment by Shpendicus** [comment]
> it's almost time for 1.89. lets wait for that. :)

When u think the 1.89 will be out, I mean the C++ main version?

**Comment by zaafar** [comment]
there haven't been 1 in last few months, so I am expecting 1 end of this month or mid of next month.

**Comment by mellinoe** [comment]
I just updated things to the latest (released) version. 1.89 should not be a difficult jump once it is released as well. Please try out the latest version on nuget.org once it shows up there.
