### ISSUE TITLE
Version 1.88 is frozen?

### ISSUE THREAD

**Issue by Shpendicus** [mellinoe/ImGui.NET#357]
I can compile it fine and even shows the demo window but I cannot click or drag anything; It remains frozen, like in a stasis. When I downgrade to 1.87.3 it works perfectly!

**Comment by zaafar** [comment]
read the text in the box.
![image](https://user-images.githubusercontent.com/5079646/197895843-3e87247e-4666-46f8-b54d-d0c671b629ea.png)

**Comment by mellinoe** [comment]
@Shpendicus I'm not seeing any issue on my end. Could you provide more info about your project and runtime environment? Also, please make sure that you clean your project fully and re-build everything after updating to 1.88.

**Comment by Shpendicus** [comment]
This project I have is a "Raylib wrapper, which makes imGui usable for the game-lib "www.raylib.com" and I made it work with **.NET 7 RC2, ImGui.NET 1.87.3 on my macosx catalina 10.15.7 and the latest Raylib version 4.2.** 

Idk what's wrong, he does not react to an input BUT when I check for input outside that DemoWindow() , the game lib Raylib, does recognize my input, so it is not due to my inputs .

![image](https://user-images.githubusercontent.com/28008874/197909091-0f44a93b-4030-4f5d-8a2b-ae689eded48c.png)

You see, he somehow still prints the 1.87.3 and I did what u suggested, upgrading, then cleaning then rebuilding still no effect .:/

**Comment by zaafar** [comment]
The input system is not part of this library. it's the responsibility of the raylib to read the input from the user and pass it to the imgui. you may wanna read imgui changelog to figure out what changed in last few versions. https://github.com/ocornut/imgui/blob/master/docs/CHANGELOG.txt#L197

**Comment by Shpendicus** [comment]
Edit:

I checked the version from the Raylib repo, which have made an imgui wrapper and tested the latest (1.88) with that one and it works, so I messed stuff up, good to know ,thx and sry!
