### ISSUE TITLE
Unknown font

### ISSUE THREAD

**Issue by Terrarxxn** [mellinoe/ImGui.NET#374]
i tried to add .ttf font using ImGui.GetIO().Fonts.AddFontFromFileTTF("C:\\Windows\\Fonts\\RS-regular.otf", 14f); but i have that 
![image](https://user-images.githubusercontent.com/69633838/208252325-73ed6057-e6db-4504-9ec7-f58fa5027002.png)

so when i clicking that my game is crashing

**Comment by Terrarxxn** [comment]
i fixed that using ImGui.GetIO().Fonts.Build(); but this is not full problem solve
i have no glyphes
![image](https://user-images.githubusercontent.com/69633838/208287159-49f04591-7a1f-45ec-8d7c-56c5a4710f1c.png)

**Comment by zaafar** [comment]
Works fine on my side (https://github.com/zaafar/ClickableTransparentOverlay/blob/master/ClickableTransparentOverlay/ImGuiRenderer.cs#L275).

**Comment by Terrarxxn** [comment]
i needd xna solution

**Comment by zaafar** [comment]
Oh, that wasn't clear from the post. Good luck!

**Comment by Hi-ImKyle** [comment]
<details>
  <summary>/off topic</summary>
  
  Any chance you can share the code you are using to get ImGui.NET to work with Terraria? I'm getting `You may not call SetData on a resource...`
  
  If you can, just add me on Discord if possible `KingFisher#0001`, or share the code on GitHub. ty  
</details>

**Comment by Hi-ImKyle** [comment]
Add fonts before you call `RebuildFontAtlas()`

**Comment by krulci** [comment]
How did you fixed this?
When I called `ImGui.GetIO().Fonts.Build()`
The overlay just disappear.
```cs
static unsafe void Font()
        {
            if (fontLoaded)
            {
                return;
            }
            ImFontConfig fontConfig = default;
            ImFontConfigPtr fontConfigPtr = new ImFontConfigPtr(&fontConfig);
            fontConfigPtr.MergeMode = false;
            //ImGui.GetIO().Fonts.AddFontDefault(fontConfigPtr);
            int[] icons = { 0xe005, 0xf8ff, 0 };
            fixed (void* iconsPtr = icons)
            {
                Console.WriteLine(FontAwesome6.FontIconFileNameFAS);
                Console.WriteLine(ImGui.GetIO().Fonts.Build());
                ImGui.GetIO().Fonts.AddFontFromFileTTF(FontAwesome6.FontIconFileNameFAS, 16.0f);
                fontLoaded = true;
            }
        }
```
