### ISSUE TITLE
Bindings for imgui_test_engine

### ISSUE THREAD

**Issue by lawrence-laz** [mellinoe/ImGui.NET#378]
[imgui_test_engine](https://github.com/ocornut/imgui_test_engine) is a library for writing automated UI tests for ImGui applications.

Would it be within the scope of this project to provide dotnet bindings to this library?

**Comment by mellinoe** [comment]
At the moment, there is no C interface for `imgui_test_engine`, so it's non-trivial to write bindings for .NET, especially given how the rest of the ImGui.NET wrapper is authored. If that changes, then we could revisit this.
