### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by cphillips83** [mellinoe/ImGui.NET#38]
I have the code as a submodule and using the latest from master. I have the following issues...

1. When calling GetStyle(), it seems like none of the colors are set. If i use PushStyleColor/Pop it works as expected.
2. If I set Alpha to 0 on the style it crashes with unable to read or write protected memory in one of the end methods.

This seems straight forward so not sure what I'm doing wrong... I've tried updating the style after different rendering times.

EDIT: To clarify, the colors are set when calling GetColor from the style, but they don't appear to be used in ImGui unless I use Push/Pop instead.

```
    public class GameWindow
    {

        private Style style;

        public GameWindow()
        {
            SetupDefaultStyle();

        }

        private void SetupDefaultStyle()
        {
            if (style == null)
                style = ImGui.GetStyle();

            style.WindowRounding = 0;
            //style.Alpha = 0f; //crashes later when calling a EndXYZ method
            style.SetColor(ColorTarget.WindowBg, new Vector4(0));
            style.SetColor(ColorTarget.MenuBarBg, new Vector4(1f, 0f, 0f, 0));
        }

        public void Update()
        {
            SetupDefaultStyle();

        }

        public void Draw()
        {


            var io = ImGui.GetIO();
            var mainMenuBarHeight = 0f;

            //ImGui.PushStyleColor(ColorTarget.MenuBarBg, new Vector4(45 / 255f, 45 / 255f, 45 / 255f, 0));
            //draw main menu bar
            {
                ImGui.BeginMainMenuBar();
                if (ImGui.BeginMenu("hello"))
                {
                    ImGui.EndMenu();
                }
                mainMenuBarHeight = ImGui.GetWindowHeight();
                ImGui.EndMainMenuBar();
            }

            {
                ImGui.SetNextWindowPos(new Vector2(0, mainMenuBarHeight + 100), Condition.Always);
                ImGui.SetNextWindowSize(io.DisplaySize - new Vector2(0, mainMenuBarHeight), Condition.Always);

                ImGui.BeginWindow("Container", WindowFlags.NoTitleBar | WindowFlags.NoMove | WindowFlags.NoResize | WindowFlags.NoCollapse | WindowFlags.NoScrollbar | WindowFlags.NoScrollWithMouse | WindowFlags.NoFocusOnAppearing | WindowFlags.NoInputs);

                ImGui.EndWindow();
            }

            //ImGui.PopStyleColor();

        }

    }
```

**Comment by cphillips83** [comment]
Additionally, this doesn't seem to work as expected, I was looking over the code in imgui and it looks like it simply has a stack of values to pop off and directly sets `style.Colors` so pushing a value should result in the style being modified and it doesn't.

```
            ImGui.PushStyleColor(ColorTarget.MenuBarBg, new Vector4(45 /255f, 45 / 255f, 45 / 255f, 0));
            var color = style.GetColor(ColorTarget.MenuBarBg);
```

**Comment by mellinoe** [comment]
I see that there are a couple of issues with how the [NativeStyle](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/NativeStyle.cs) structure is defined. It has fallen out of sync with some breaking changes in the native structure: https://github.com/ocornut/imgui/blob/55a6209931a145dd012e85e6673e5ef6575948c9/imgui.h#L736.

I will sync them up and provide a commit for you to try out.

**Comment by cphillips83** [comment]
I swear this is one of the first things I looked at and some how missed it. Anyways, i copied the struct from imgui and changed corrected the types and it now works. Still find at strange that Alpha would cause it to crash even though it was first in the struct in both with the same type.

**Comment by mellinoe** [comment]
@cphillips83 Great -- I pushed a similar change to master which fixes the definition. I still get a crash when I try to set Alpha = 0, but I'm wondering if that is something else entirely. Everything works as expected when I set Alpha = 0.00001f, but 0 always causes a crash. Reading around the code in imgui, it seems like Alpha = 0 SHOULD be supported, though...

**Comment by cphillips83** [comment]
https://github.com/ocornut/imgui/blob/302757447aa6f0eed177e6cb33de887242a6355e/imgui.cpp#L2850 Not sure I understand this comment.

**Comment by cphillips83** [comment]
Ah, I misunderstood the reason behind Alpha, I was expecting it to be a baseline level for most alpha related things but it is actually a alpha level for everything rendered. Still shouldn't crash, but Alpha = 0 also doesn't make sense since you would render nothing.

**Comment by mellinoe** [comment]
Interesting. It looks like Alpha=0 is treated specially in at least one place. I debugged through my crash and, without really diving too deep into it, the program crashes because it tries to pop two style variables [here](https://github.com/ocornut/imgui/blob/302757447aa6f0eed177e6cb33de887242a6355e/imgui.cpp#L9224) and there are 0 in the stack.

I think it'd be hard to do anything here unless I knew it was an issues in ImGui.NET (but it doesn't seem like it is anymore). In any case, it probably doesn't make any sense to set the global Alpha to 0, like that comment is suggesting.

**Comment by cphillips83** [comment]
Correct, I'll go ahead and close this. Thanks!
