### ISSUE TITLE
ShowBorders

### ISSUE THREAD

**Issue by cphillips83** [mellinoe/ImGui.NET#39]
Seems like WindowFlags.ShowBorders is ignored. Looking at the imgui this was built against, it seems if show border is set to true it will simply draw a 1px border but I can't get it to.

Newer version of imgui .net have created a border size in the style struct, any eta on this?

**Comment by mellinoe** [comment]
@cphillips83 ShowBorders seems to work for me. 

Without borders:

![image](https://user-images.githubusercontent.com/8918977/33098059-ef6f352a-cec0-11e7-9320-d83ed3ef403f.png)

With borders:

![image](https://user-images.githubusercontent.com/8918977/33098069-f7817ba6-cec0-11e7-8ba0-e045524ef551.png)

The effect is really subtle and might depend on how your styles are set up.

Test code:

```C#
WindowFlags showBorders = _showBorders ? WindowFlags.ShowBorders : WindowFlags.Default;
ImGui.BeginWindow("ImGUI.NET Sample Program", ref _mainWindowOpened, WindowFlags.NoResize | WindowFlags.NoTitleBar | WindowFlags.NoMove | showBorders);
...
if (ImGui.Button("Show borders"))
{
    _showBorders = !_showBorders;
}

```

**Comment by cphillips83** [comment]
So it seems like its not a real border but a 1px padding? My issue is on the Window, if I set show borders it seems like it just insets everything but the title by 1px and the border is the background of the window?

            var style = ImGui.GetStyle();
            style.WindowRounding = 5;
            var windowBg = style.GetColor(ColorTarget.WindowBg);
            windowBg.W = 0;
            style.SetColor(ColorTarget.WindowBg, windowBg);

**Comment by mellinoe** [comment]
Yeah, the border should appear on all of the child items in the window that it is set on:

![image](https://user-images.githubusercontent.com/8918977/33098973-0bab9f00-cec4-11e7-9499-fd05a750cdc7.png)

As far as I know, there isn't a way to set a border on the main menu.

**Comment by cphillips83** [comment]
No border
![image](https://user-images.githubusercontent.com/6414193/33099490-08748a48-cedf-11e7-91ae-7728b8c1ceaa.png)

With border

![image](https://user-images.githubusercontent.com/6414193/33099502-0feb3e7a-cedf-11e7-9fb6-f995a0ea679b.png)

```
            style.SetColor(ColorTarget.Border, new System.Numerics.Vector4(1, 0, 0, 1));
            style.SetColor(ColorTarget.WindowBg, new System.Numerics.Vector4(0,1,0,1));
```

Not sure what I'm missing here?

**Comment by cphillips83** [comment]
Wow, the borders are being drawn in reverse order. Once I set culling mode to None they now appear. Not sure if imgui clears about the vertex order and just assuming no culling since its a UI of course.

**Comment by mellinoe** [comment]
Yeah, it should be drawn without any culling.
