### ISSUE TITLE
How do I use ImGuiListClipper for drawing a flow container of tiles

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/ImGui.NET#393]
I am trying to simulate a scroll area and only draw the visible tiles...

```cs
                    var size  = ImGui.GetContentRegionAvail();
                    var index = 0;
                    var count = Tiles.Length;

                    var clipper = new ImGuiListClipperPtr();
                    clipper.Begin((int)(size.X * size.Y), TileSizeY);


                    for (var i=0; i<Tiles.Length; i++)
                    {
                        if (ImGui.GetItemRectMax().X < size.X) ImGui.SameLine();

                        var image = Image(Tiles[index].GetTexture(), new(1,0), new(0,1));
                        Raylib.BeginTextureMode(image);
                        Raylib.DrawRectangleLines(0,0, TileSizeX, TileSizeY, Color.WHITE);
                        Raylib.EndTextureMode();
                        index++;
                    }
                    clipper.End();
```

- How exactly does the .net version of the listclipper work>?
- How would I simulate a fake scroll area without looping 60000 times?
- How do I get the min and max rows and columns of the visible scroll area?

**Comment by Shadowblitz16** [comment]
ListClipperPtr crashes the program and there is no ImGuiList class to pass to it's constructor

**Comment by sonoro1234** [comment]
https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L5658

**Comment by Shadowblitz16** [comment]
yes it crashes.
Also please provide C# code when people ask for examples ListClipper doesn't have a Begin, Step or End method only ListClipperPtr does so the c++ api is not a good refrence

**Comment by TheLostTree** [comment]
Confirming that ListClipperPtr crashes for me as well :(

**Comment by TheLostTree** [comment]
Nevermind! I figured out that using this works without crashing

```cs
ImGuiListClipperPtr listClipper = new ImGuiListClipperPtr(ImGuiNative.ImGuiListClipper_ImGuiListClipper());
```

**Comment by ocornut** [comment]
I have also pushed a workaround on dear imgui side:
https://github.com/ocornut/imgui/commit/e95d66faa8e6c0255572632f34fad97a32f680cd
