### ISSUE TITLE
Input problem on OSX

### ISSUE THREAD

**Issue by stakira** [mellinoe/ImGui.NET#41]
Using trackpad, sample program always show
```
Current Mouse Position = <-9999,-9999> Pressed=false
```
Using a USB mouse, `Pressed` does respond, but `Current Mouse Position` is still the same

Using macOS Sierra version 10.12.6 and dotnet SDK 1.1.5

Tried
```
dotnet restore -r osx.10.11-x64
dotnet publish -c release -r osx.10.11-x64
```
and
```
dotnet restore -r osx.10.12-x64
dotnet publish -c release -r osx.10.12-x64
```
Same results.

**Comment by mellinoe** [comment]
The sample project no longer uses OpenTK, which was likely the cause of this problem. Feel free to re-open if the new sample project still exhibits problems.
