### ISSUE TITLE
A more complete sample that better aligns with the ImGui samples

### ISSUE THREAD

**Issue by liquidboy** [mellinoe/ImGui.NET#42]
Not sure if you want this contribution BUT as part of learning about this library I'm planning on porting a more complete version of the samples across from ImGui ..

My repo is here and happy to raise pull requests when done if you want the samples : https://github.com/liquidboy/ImGui.NET

**Comment by mellinoe** [comment]
I would definitely want this. The current sample was hacked together in an hour or so, and it's very, very messy. And it doesn't do anything interesting.

**Comment by mellinoe** [comment]
I've re-written the sample project, and I think the new one is significantly better than before. It is adapted from the official example code.
