### ISSUE TITLE
v1.52?

### ISSUE THREAD

**Issue by Catvert** [mellinoe/ImGui.NET#43]
Hi !
I noticed that version 1.52 of cimgui had been released for some time so I wonder when you plan to upgrade ImGui.Net to this new version? 
Thanks, Catvert.

**Comment by mellinoe** [comment]
I was waiting for cimgui to be updated as well, but it looks like that happened a while ago, too. I will try to set aside some time this week to update ImGui.NET.

**Comment by Catvert** [comment]
Nice it's a good news ! :)

**Comment by mellinoe** [comment]
It turns out 1.53 came out yesterday. I may need to update cimgui myself, but that would probably be a better version to target.

**Comment by Catvert** [comment]
Oh, great! I look forward to it! 
Thank you for your engagement! 😃
