### ISSUE TITLE
Thoughts: Change assembly versioning to match imgui

### ISSUE THREAD

**Issue by mellinoe** [mellinoe/ImGui.NET#44]
I'm considering changing ImGui.NET's assembly versioning to follow the versioning of imgui's -- at least partially. It probably makes sense to use a scheme like x.y.z, where x.y is the imgui version (currently 1.53), and z is a patch version for minor fixes made to ImGui.NET itself. This would make it a lot easier to tell which version of imgui you are getting with a particular version of ImGui.NET, since you currently need to crawl through the commit history to do that.

The only downside is now there will be an unusual bump from 0.4.0 to 1.53.0. Not a big deal, but it might be confusing initially.

**Comment by wizzard0** [comment]
How about 0.4.1.53 or 0.4.153?

**Comment by mellinoe** [comment]
I'd also like the NuGet package version to match up with this, so realistically there's only 3 numbers to work with. Your latter idea could work, although it might be a bit weird to combine the two digits into a single number. There could be potential issues if the imgui version rolls over to 1.100, although that's probably unlikely...

**Comment by dpethes** [comment]
I don't see any issue with such a jump: I imagine that what one usually wants is a new version, and the easier is to find the matching imgui version the better (I don't use imgui.net assembly, but it applies to other "wrappery" projects I use).

**Comment by mellinoe** [comment]
I will likely switch to this convention when the 1.60+ update happens.

**Comment by mellinoe** [comment]
I'm following this from now on, and the newest versions will start from 1.65.0 (Dear ImGui 1.65).
