### ISSUE TITLE
Glyph range font ?

### ISSUE THREAD

**Issue by Catvert** [mellinoe/ImGui.NET#49]
Hi !
I'm looking to specify a glyph range when I load a ttf font but I've found nothing related.
The problem appear when I want to display text with accent (eg é, è..)

Thanks for your help, Catvert.

**Comment by Catvert** [comment]
While we're at it, I have a few other questions, where are the ItemFlags (for example to deactivate an item, PushItemFlag?), is it implemented?. 
I have an other issue with PopupModal, eg : 

```cs
 ImGui.OpenPopup(id);
 ...
 if (ImGui.IsPopupOpen(id)) {
       ImGui.BeginPopupModal(id, ref opened, flags);
       ImGui.Text("hi");
       ImGui.EndPopup();
 }
```
The popup looks good as expected but when I click on the cross to close the popup, I have an AccessViolationException from ImGui.Render().

Thanks, Catvert.

**Comment by dpethes** [comment]
See https://github.com/mellinoe/ImGui.NET/pull/37

**Comment by mellinoe** [comment]
Unfortunately, UTF8 isn't properly supported at the moment. We need to do a semi-major overhaul of all of the native functions in order to properly support it.

As for your modal popup: you need to be checking the return value of `BeginPopupModal`, and only call `EndPopup` when it is true. You don't need to call `IsPopupOpen` at all there.

```
if (ImGui.BeginPopupModal(id, ref opened, flags))
{
       ImGui.Text("hi");
       ImGui.EndPopup();
 }
```

**Comment by Catvert** [comment]
Thank you for your help, I am looking forward to the arrival of the UTF8 support ! :)

**Comment by Catvert** [comment]
Hi !
I reopen the issue because you forgot to answer one of my questions, is it possible to deactivate an item, make it inactive, (e. g.: a delete button when there are not items)?

**Comment by ocornut** [comment]
`PushItemFlag` is an internal api in the main imgui repo, not exposed in imgui.h, and the Disabled feature isn’t finished. I would say if you want to use it you may wrap it yourself but it seems adequate to me to not provide it in the public library.

**Comment by mellinoe** [comment]
@Catvert Oops, sorry for not catching that last question. @ocornut obviously knows the most about upcoming features 😄.

It's not exactly ideal, but when I've wanted to do that (have a disabled button, that is), I just set its alpha to something low and have it ignore interactions. Obviously, you can still press it, but the fact that it's grayed out gets the point across, IMO. For example:

![image](https://user-images.githubusercontent.com/8918977/37141166-0a00202e-2269-11e8-957a-4fb9b08edabb.png)

vs.

![image](https://user-images.githubusercontent.com/8918977/37141182-190ca0ec-2269-11e8-9aac-58bf34d6ddac.png)

is clear enough for my uses, although it's not perfect.

**Comment by Catvert** [comment]
Hi !
I will try to create my own solution like yours while waiting the disabled feature.  
Thanks for your helps :) !
