### ISSUE TITLE
Add ListBox to ImGui wrapper class

### ISSUE THREAD

**Issue by tgjones** [mellinoe/ImGui.NET#50]
Me again :)

I'm just getting started with ImGui.NET (having no prior experience with imgui). One of the first things I tried was creating a `ListBox`, but although this exists in `ImGuiNative`, it doesn't appear to be wrapped in `ImGui`. Am I missing something, or is this really not implemented?

If not, I'm happy to do a PR for it.

**Comment by tgjones** [comment]
I've found the (very powerful) `Selectable`, which seems to let me build something like a listbox very easily. So I don't think I need this one anymore - please feel free to close it unless you want to keep it open.

**Comment by mellinoe** [comment]
@tgjones I've not actually used `ListBox` myself, and it is a really unusual function. It takes a callback, which is very rare for any functions in the library. As you've found, you can very easily create multiple options using the `Selectable` function.

Adding a wrapper for `ListBox` would be fine if anyone else is interested, but I'll close this for now.
