### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by Masclaux** [mellinoe/ImGui.NET#53]
Hello

When I run the sample with openTK  it's look like clipboard is  natively managed. With my implementation who use SDL2  ( OpenTK for gl call) I don't have access to this function (ctrl-V, ctrl-C, ctrl-X).

It's not really an issue but if someone has managed to integrate IMGUI with SDL2CS can he say me if clipboard is native or I need to to do some stuff with  GetClipboardTextFn and   SetClipboardTextFn ? 

Thanks !

**Comment by Masclaux** [comment]
Hello.

I'm currently on Windows That why I find odd that clipboard is not supported.

**Comment by mellinoe** [comment]
@Masclaux Hmm, in that case, it should just work. I use SDL2 in most of my projects, as well. On Windows, the clipboard has always seemed to work correctly for me without setting any of the imgui function pointers. Can you share any more information about what is or isn't working, or about how your project is set up?

**Comment by Masclaux** [comment]
Hum weird .

For my project I have SDL2-CS (last version 2.0.0.8 for the native part ) and opentk.

I create the GL context with SDL and send it to TK. My IMGUI integration is based of the sample with the same example. (see in https://github.com/mellinoe/ImGui.NET/issues/34)

I just remove for the  GL Scissor part, I see with the debugger IMGUI return Texture ID == 0 and ithis Id is different from the real IMGUI Texture who I create with my engine.

Tomorrow if I have time I can directly create a sample with only SDL.

**Comment by Masclaux** [comment]
Re,

Stupid bug for stupid code :) 

I found the solution after checking a basic implemenation with sdl2.

I'm updating my modifiers state every frame and re-building my Keyboard event. But that can't work because I do that at the end of frame and the modifiers return to false.

Now my key event have modifiers at the time when I get them.

Sorry for the incovenience and thank you for you works.

**Comment by mellinoe** [comment]
No problem, I'm glad you discovered the problem.
