### ISSUE TITLE
Strange code in sample renderer

### ISSUE THREAD

**Issue by Alan-FGR** [mellinoe/ImGui.NET#54]
Hey there :)

I was taking a look at the sample renderer in order to help somebody at the imgui gitter, and found somethings I can't make sense of:

https://github.com/mellinoe/ImGui.NET/blob/1826f494b64af97ad5c48f761c56f6646932e222/src/ImGui.NET.SampleProgram/SampleWindow.cs#L403-L405
https://github.com/mellinoe/ImGui.NET/blob/1826f494b64af97ad5c48f761c56f6646932e222/src/ImGui.NET.SampleProgram/SampleWindow.cs#L426-L427

I believe these are bogus code, but I could be wrong because I'm just browsing from the web.

**Comment by mellinoe** [comment]
Could you be more specific? This is unsafe code, which might look weird to you. It's completely valid, though, and is being used in the demo program.

**Comment by Alan-FGR** [comment]
Well, the vertX vars and the indices[] array don't seem to be used, anywhere... but then again I could be wrong... and yeah I know unmanaged stuff.
I'll try cloning and removing those lines... hang on a sec

**Comment by Alan-FGR** [comment]
git clone --recursive https://github.com/mellinoe/ImGui.NET.git

**Comment by Alan-FGR** [comment]
OK, right away the editor says the vertX vars aren't used... I gotta download the net core stuff to build

**Comment by mellinoe** [comment]
Oops, you are correct, that stuff is unused. I've removed it in the latest commit.

**Comment by Alan-FGR** [comment]
OK, it's not gonna happen, can't build it here, but I can tell you that the indices array doesn't seems to do anything at all, it's not a ptr, you're creating a managed array and populating with the data in the idx_buffer (which is a ptr) and then not using it.

**Comment by Alan-FGR** [comment]
Darn... ninjaed :laughing:

**Comment by mellinoe** [comment]
Sorry for the confusion 😄. It was probably just debug code that I forgot to remove a long while back. By the way, this sample code is adapted directly from the original repo's demo [here](https://github.com/ocornut/imgui/blob/master/examples/opengl2_example/imgui_impl_glfw_gl2.cpp#L62).
