### ISSUE TITLE
Issue with DLL

### ISSUE THREAD

**Issue by Sphinksz** [mellinoe/ImGui.NET#57]
1. Added ImGui.NET to project via NuGet. (Also tried downloading project and building it and adding dll from release folder.

2. Added reference in .cs

        using ImGuiNET;

3. Added code just to add basic window.

        private void ImguiTest()
        {
            ImGui.BeginWindow("Test");
            ImGui.Text("Hello,");
            ImGui.Text("World!");
            ImGui.EndWindow();
        }

Getting error: 
System.DllNotFoundException: 'Unable to load DLL 'cimgui': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

Not sure the issue?

**Comment by mellinoe** [comment]
@Sphinksz If you're using .NET Framework (as opposed to .NET Core), then you need to manually deploy the native binary from the NuGet package. cimgui.dll is located at `runtimes/native/win-x64/cimgui.dll` inside of the package.

.NET Core projects will find and deploy the native binary for you automatically.

**Comment by Sphinksz** [comment]
Appreciate it Mell. I'll try that!

**Comment by Sphinksz** [comment]
Good to go mell. Appreciate your work

**Comment by mellinoe** [comment]
Happy to help, cheers.

**Comment by TheRealNOIG** [comment]
How would I solve this issue on linux. I cant figure out how to point the dll to the linux .so file
