### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by slicol** [mellinoe/ImGui.NET#59]
我用VS2015打不开Git上的Sample工程
我自建了一个工程，把代码导入后，也运行不了
![image](https://user-images.githubusercontent.com/1841697/43238540-2823e6e6-90c1-11e8-9669-ccf35049b693.png)

**Comment by mellinoe** [comment]
@slicol Unfortunately, I don't think .NET Core projects work with VS 2015. It should work better with VS 2017.

You could also try to run the project from the command line:

`dotnet run -p src\ImGui.NET.SampleProgram\ImGui.NET.SampleProgram.csproj`

**Comment by slicol** [comment]
Thank you very much~
