### ISSUE TITLE
Auto-generate the native binding and marshalling code

### ISSUE THREAD

**Issue by mellinoe** [mellinoe/ImGui.NET#61]
In order to improve the maintainability of the library, I'm working on generating the native binding and marshalling code, building on top of the [auto generated C bindings](https://github.com/ocornut/imgui/issues/1879). This will allow me to generate struct and function definitions from pre-processed JSON files which include all the information I need, and which will be automatically updated with new imgui versions. We should also be able to get benefits like Unicode support much more easily with this approach, because we can spit out a lot of annoying boilerplate automatically. The [autogen](https://github.com/mellinoe/ImGui.NET/tree/autogen) branch includes the current state of this work.

This will likely involve some breaking changes in the API. Newer versions of imgui (1.60+) already include a number of breaking changes that folks will have to react to anyways, so I think it is a good time to break things.

**Comment by timgroote** [comment]
Is the autogen branch going to get its own NuGet package?

**Comment by mellinoe** [comment]
@timgroote I wasn't planning on it. Ideally it doesn't remain forked off into its own branch for very long, but I need to dedicate some time to getting it usable first. At the moment it's not usable so a NuGet package wouldn't be of much use anyways.

**Comment by mellinoe** [comment]
This is done.
