### ISSUE TITLE
SliderInt with custom display format has incorrect value

### ISSUE THREAD

**Issue by SamVanheer** [mellinoe/ImGui.NET#64]
When using a SliderInt with a non-null display format, the format is respected but the value used for %d is incorrect.
When the slider is not being changed the value is 0.
When it is being changed the value seems to be completely random.

Here's the code i used to test this, in the sample program's `SubmitUI` method, under the SliderFloat example:
```
int fps = 10;

 ImGui.SliderInt("int", ref fps, 0, 60, "%d");
```

Even if fps is made static to retain the value it still happens.

The SliderFloat does work correctly when using format `%0.1f`, which leads me to assume that something is wrong with the specific type used, but the native demo's SliderInt works correctly.

I think it's caused by this code: https://github.com/ocornut/imgui/blob/ec04e8bb050ef42f25aee6e5748f4e0e153266bf/imgui_widgets.cpp#L2295

It only does this if the type is int32 but the strcmp should return 0 if i pass "%d", so i'm not sure what's going on here. I tried to marshal the display format as an ANSI string to see if encoding mattered, but that didn't do anything.

I've also noticed that there's an unused igSliderFloat overload that takes a `float*`, could this be related somehow?

**Comment by mellinoe** [comment]
I'm going to assume this one is fixed; feel free to re-open if you still see it.

**Comment by SamVanheer** [comment]
I tested it and it's working now.
