### ISSUE TITLE
[autogen] ImGuiMouseCursor enum

### ISSUE THREAD

**Issue by pragmascript** [mellinoe/ImGui.NET#66]
Hey, 

the generated `ImGuiMouseCursor` enum seems to be offset by one starting from `ImGuiMouseCursor.TextInput`.

compare:
https://github.com/ocornut/imgui/blob/781a7950d764c44ab59b520f01b2946adcce313a/imgui.h#L1005

and:
https://github.com/mellinoe/ImGui.NET/blob/autogen/src/ImGui.NET/Generated/ImGuiMouseCursor.gen.cs#L7

**Comment by mellinoe** [comment]
This one is fixed now. Thanks for catching this!
