### ISSUE TITLE
[Suggestion] Support Chinese Language

### ISSUE THREAD

**Issue by a348019017** [mellinoe/ImGui.NET#67]
I add the code in Imgui like this.
![image](https://user-images.githubusercontent.com/12935754/46243828-6f404480-c40a-11e8-910c-49ef7ca667a8.png)
then I modify the addFontbyFile function just follow imgui samples.
![image](https://user-images.githubusercontent.com/12935754/46243847-aa427800-c40a-11e8-93e3-f2dc1e4080d4.png)
but is did not work just show chinese as ???.

**Comment by mellinoe** [comment]
You need to pass a valid `glyph_ranges` pointer for the last parameter. I've tested the following, and I'm able to render some Chinese characters:

```C#
var fontAtlas = ImGui.GetIO().Fonts;
fontAtlas.AddFontFromFileTTF(
    @"c:\Windows\Fonts\ArialUni.ttf",
    16f,
    null,
    fontAtlas.GetGlyphRangesChineseFull());
```

This is using the new 1.65.0 beta version of the library. I've actually pushed a small change to the code generator to make dealing with glyph ranges easier.
