### ISSUE TITLE
System.TypeInitializationException when running the SampleProgram

### ISSUE THREAD

**Issue by se5a** [mellinoe/ImGui.NET#68]
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Veldrid.Sdl2.Sdl2Native' threw an exception. ---> System.InvalidOperationException: No function was found with the name SDL_SetWindowOpacity.
   at NativeLibraryLoader.NativeLibrary.LoadFunction[T](String name)
   at Veldrid.Sdl2.Sdl2Native..cctor()
   --- End of inner exception stack trace ---
   at Veldrid.Sdl2.Sdl2Native.SDL_Init(SDLInitFlags flags)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd)
   at ImGuiNET.Program.Main(String[] args) in /mnt/98448323-4372-4c8a-904a-30b587cc3685/Programing/ImGui.NET/src/ImGui.NET.SampleProgram/Program.cs:line 30
bash: line 1:  8142 Aborted                 /usr/share/dotnet/dotnet "/mnt/98448323-4372-4c8a-904a-30b587cc3685/Programing/ImGui.NET/bin/Debug/ImGui.NET.SampleProgram/netcoreapp2.0/ImGui.NET.SampleProgram.dll"

Press any key to continue...
```

I've an older (around June) copy of the repository which appears to be run the SampleProgram fine, its been a while since I looked at this and I don't remember if I did anything special to get that running. 
I'm compiling and debugRunning in MonoDevelop on Linux mint.

**Comment by mellinoe** [comment]
The version of SDL2 that you have installed on your machine doesn't seem to have one of the expected functions. Are you able to update it in your package manager?

**Comment by se5a** [comment]
ah. I see. 
apt seems to think I'm on the latest version at 2.0.4 but SDL_SetWindowOpacity is 2.0.5, and looks like the latest version is 2.0.8 I guess I gota go figure out how come apt thinks 2.0.4 is the latest version.

**Comment by mellinoe** [comment]
I've filed https://github.com/mellinoe/veldrid/issues/125 over in Veldrid so that I can improve this behavior. Getting your version of SDL2 updated will be the quickest fix, but long-term I'd like to support lower versions as long as they have the necessary functions available (SDL_SetWindowOpacity is not essential).

**Comment by se5a** [comment]
Mint 19 apparently has the SDL versions, in the repos but 18 (which I'm currently using) doesn't. 
right now I'm away from home on limited internet and don't want to risk updating to 19 just yet, but I should be able to update SDL on it's own.

**Comment by se5a** [comment]
Don't suppose anyone here can tell me how to update SDL to the latest version? I've tried building and installing it from source but I'm still running into the same problem, I expect it's not installing something I need but I'm unsure what.  
I tried updating to linux mint 19 which would have fixed the problem as I would have been able to just install it from the repositories... but that failed somewhat catastrophically and I messed around with that for a number of hours before giving up and restoring a snapshot.

**Comment by mellinoe** [comment]
Hm, this stuff can get pretty tricky depending on what state your machine is (e.g. what other packages you have installed and what they depend on). Building from source should be a straightforward option, though.

> I've tried building and installing it from source but I'm still running into the same problem

Did you uninstall the version from the package manager as well? It's possible that they are both on your `LD_LIBRARY_PATH`, but the 2.0.4 version is ahead of it in the list. Either changing that order or uninstalling the old version could work.

**Comment by se5a** [comment]
Uninstalling and re-installing 2.0.8 worked... I think, however now I'm running into problems with vulkan: 

```Unhandled Exception: System.TypeInitializationException: The type initializer for 'Vulkan.VulkanNative' threw an exception. ---> System.InvalidOperationException: Could not load libvulkan.so.1
   at Vulkan.NativeLibrary..ctor(String libraryName)
   at Vulkan.NativeLibrary.Load(String libraryName)
   at Vulkan.VulkanNative..cctor()
   --- End of inner exception stack trace ---
   at Vulkan.VulkanNative.vkEnumerateInstanceLayerProperties(UInt32& pPropertyCount, VkLayerProperties* pProperties)
   at Veldrid.Vk.VulkanUtil.EnumerateInstanceLayers()
   at Veldrid.Vk.VkGraphicsDevice.CreateInstance(Boolean debug)
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc)
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd)
   at ImGuiNET.Program.Main(String[] args) in /mnt/98448323-4372-4c8a-904a-30b587cc3685/Programing/ImGui.NET/src/ImGui.NET.SampleProgram/Program.cs:line 30
bash: line 1: 22270 Aborted                 /usr/share/dotnet/dotnet "/mnt/98448323-4372-4c8a-904a-30b587cc3685/Programing/ImGui.NET/bin/Debug/ImGui.NET.SampleProgram/netcoreapp2.0/ImGui.NET.SampleProgram.dll"
```

I'll try installing vulkan-utils incase that's what I'm missing, I feel this is a problem with Linux, you run into dependency problems and its never clear exactly what one needs.

**Comment by mellinoe** [comment]
I’m glad to hear it’s working for you now. Could I ask which commit you were testing when you hit the Vulkan error? I noticed that the sample was always trying to create a Vulkan device even it it wasn’t supported, so I switched it a few days ago to fall back to OpenGL if Vulkan fails. Were you testing a commit before that?

**Comment by se5a** [comment]
I don't think I've git pulled for ages, looks like it was commit b5407eeba507fa85411364152e121b8f843693d1 from 29 Aug. 
I might remove vulkan-utils and pull the latest and see if it works from that state, anything that reduces dependency issues is good imho. 

I'm looking at converting something I started with imgui-cs to imgui.net, as 0x0ade appears to have removed imgui-cs from github completely. Now I've got the sample running I'm hoping most the conversion will be just syntax.

**Comment by mellinoe** [comment]
Correct, the CodeGenerator project is just needed if you intend to regenerate the code under ImGui.NET/src/Generated. The generated files are checked in, so you don't need it unless you are making modifications to the generator or building for a different branch of cimgui.

**Comment by mellinoe** [comment]
OpenTK is just a wrapper over OpenGL (and various other things), whereas Veldrid is a portable graphics library that runs on top of lots of different API's (Vulkan, GL(ES), D3D, Metal) on different platforms. It's also designed to be very usable from C#, as opposed to native API's which can be a bit unfriendly from higher-level languages. It may or may not be important to you, but Veldrid also supports .NET Core, which is significantly faster than other runtimes. The [docs](https://mellinoe.github.io/veldrid-docs/) have a better introduction / overview. Feel free to join [the Gitter room](https://gitter.im/veldrid/Lobby) if you want to learn more about it.
