### ISSUE TITLE
[autogen] SetCursor / GetCursor inconsistent

### ISSUE THREAD

**Issue by pragmascript** [mellinoe/ImGui.NET#69]
I ran into an issue with GetCursor and SetCursor:

Calling `ImGui.SetCursor` with the result of `ImGui.GetCursor` should be a noop, but it's not.

ImGui.NET:

```csharp
public void DrawTestWindow() {
    ImGui.Begin("TestWindow");

    ImGui.Button("more button 1");
    ImGui.Button("more button 2");

    var tempCursorPos = ImGui.GetCursorPos();
    ImGui.SetCursorPos(tempCursorPos);

    ImGui.Button("more button 3");
    ImGui.Button("more button 4");

    ImGui.End();
}
```
<img width="164" alt="imgui_net" src="https://user-images.githubusercontent.com/314603/46478021-5362e700-c7ec-11e8-8b60-8444e103d7bc.PNG">

ImGui:
```cpp
void draw_test_window(void) {
    ImGui::Begin("TestWindow");

    ImGui::Button("more button 1");
    ImGui::Button("more button 2");

    ImVec2 tempCursorPos = ImGui::GetCursorPos();
    ImGui::SetCursorPos(tempCursorPos);

    ImGui::Button("more button 3");
    ImGui::Button("more button 4");

    ImGui::End();
}
```

<img width="172" alt="imgui_cpp" src="https://user-images.githubusercontent.com/314603/46478059-6b3a6b00-c7ec-11e8-852e-f8170570db82.PNG">

**Comment by mellinoe** [comment]
Hm, can you try the very latest from autogen? With your code, I'm not seeing any issue. Either my changes yesterday fixed it, or it's not happening on my machine.

**Comment by pragmascript** [comment]
Okay, I tried it with the latest changes. I still have the same issue. Maybe I am doing something wrong in my renderer.

**Comment by mellinoe** [comment]
Are you running a 64-bit program? I’ve only updated the win-x64 binary in the auto gen branch as of yet. Things will probably be more or less broken on 32-bit until I do that, but I was waiting until the rest of the changes were in.

**Comment by pragmascript** [comment]
Yes, I am using the win-x64 version of cimgui.

**Comment by mellinoe** [comment]
Are you able to test your snippet inside the sample program checked into the autogen branch? That’s where I tried it out successfully.

**Comment by pragmascript** [comment]
I restructured my OpenGL Controller and the issue has gone away. I'm still not quite sure what caused the issue but It was probably something on my end. :/

**Comment by pragmascript** [comment]
I tracked it down and it only happens for me when I use DPI scaling. And it only happens on Debug builds and not on Release builds. 
On Debug builds the result of ImGui.GetCursor() is just wrong and I have no clue why.

release build (correct result):
<img width="200" alt="correct" src="https://user-images.githubusercontent.com/314603/46573222-69aaa780-c992-11e8-8f5e-b4f3d012b48a.png">

debug build (wrong result):
<img width="267" alt="wrong" src="https://user-images.githubusercontent.com/314603/46573223-6c0d0180-c992-11e8-9504-3dbef56b2930.PNG">
The only difference between the two images is Debug build vs. Release build.

```csharp
 public void DrawTestWindow() {
            ImGui.Begin("TestWindow");
            ImGui.Button("more button 1: " + ImGui.GetCursorPos());
            ImGui.Button("more button 2: " + ImGui.GetCursorPos());
            ImGui.Button("more button 3: " + ImGui.GetCursorPos());
            ImGui.Button("more button 4: " + ImGui.GetCursorPos());
            ImGui.End();
        }
``` 
I could not reproduce this issue with ImGui.Net sample application yet.
