### ISSUE TITLE
Native string handling issues

### ISSUE THREAD

**Issue by dpethes** [mellinoe/ImGui.NET#7]
Hi, seems that .net is unable to cope with strings returned from igGetVersion & igGetClipboardText (crashes) - usually when they contain non-ascii chars. One solution is to change the return type to byte* and convert it through Encoding.UTF8 like this: https://gist.github.com/dpethes/4d667c7c1db65890f114f0ccc1833582 Manually searching the string's end seems a bit out of place though, any better ideas?

**Comment by dpethes** [comment]
After some experiments it seems like the proper solution would be to
* convert string parameters in imported functions (ImGuiNative) to byte pointer (at least in those functions that display the texts, like igButton, igText family etc)
* wrap those functions in ImGui and encode/decode strings to/from utf8 bytes
* profit

Any objections?

**Comment by mellinoe** [comment]
Yes, that seems like the correct approach to take. 👍

**Comment by dpethes** [comment]
Work in progress, let me know if you have any suggestions: https://github.com/dpethes/ImGui.NET/tree/text_improvements

**Comment by dpethes** [comment]
Another possible solution - create a wrapper dll for the methods using strings that would accept widestrings from .net and convert them to utf-8 for imgui (and back).

**Comment by mellinoe** [comment]
@dpethes I took a look at your branch. The approach looks good overall, although I'm concerned with the amount of temporary allocations that are being made. Newer versions of .NET Standard expose `Encoding` overloads which allow allocation-less operations. Given how IMGUI code is used (and how often each method is called), I think it's really important that we aren't creating tons of unnecessary garbage for the GC.

> Another possible solution - create a wrapper dll for the methods using strings that would accept widestrings from .net and convert them to utf-8 for imgui (and back).

I'd prefer that we don't need to make any changes to cimgui (that sounds like what you're alluding to), or create any other native wrappers. Every native dependency makes deployment that much harder, and just splits up the logic unnecessarily. I think doing all of the encoding conversions in C# is feasible.

**Comment by dpethes** [comment]
Which version of .Net Standard / Encoding overload do you mean? If it means less code / unsafe / pointers / etc, I'm all for it (while I'm somewhat interested in running it on .Net framework 4.0 with utf8 support, it's not that important). I also wonder how other projects handle this, surely widestring -> utf8 string conversion for native interop can't be unique for imgui.net.

I generally agree, but it's quite a pain so far and I was thinking about other ways how to avoid this :)

**Comment by dpethes** [comment]
Another idea: statically allocate "big enough" pool (stackalloc? GCHandle.Alloc?) for string conversions and track its usage. When calling a wrapped native method:
* set bytes_used counter to 0
* pass slices of it to Encoding.GetBytes Method (Char*, Int32, Byte*, Int32) and increase bytes_used accordingly (if the buffer is not big enough, throw exception)
* call native imgui function

This is obviously not thread safe, but ImGui isn't either afaik. The reverse function (string from native) would have to use GetString(Byte*, Int32), which is .Net >= 4.5. Is this what you were hinting at?

**Comment by dpethes** [comment]
This is what I came up: https://gist.github.com/dpethes/46f08c88bac0822fda05db4152fd00b2
Thoughts?

**Comment by mellinoe** [comment]
Here's what I had in mind:

https://github.com/mellinoe/ImGui.NET/commit/a090b24695eb407393ee708fd5d38faab0fe28eb#diff-a70f0516d95aca67febe9a622d35b653R82

It just uses stackalloc of the appropriate length, gets the encoded bytes, and calls `igText` with that stackalloc'd pointer.

We could have a stack allocation limit (4k or something?), and fall back to a statically-allocated persistent buffer, like the example you shared. We could make it a thread-local shared buffer if we are concerned about threading.

**Comment by dpethes** [comment]
I tried something similar with stackalloc: 
* always allocate (message.Length * 4 + 1) bytes, so you don't have to call GetByteCount()
* pass the pointer to allocated bytes to modified FromStr(), so the conversion code is shared between functions

But I disliked it because it needs more code at the caller's side. I'm trying to avoid that, because it means plenty of repeated code in a lot of functions (and harder modifications).

I also realized that I don't need to do the Reset() call when using the Utf8Buffer. If there isn't any space left in the buffer for the converted string, it can just start from the beginning again. This is ok, assuming one ImGui call doesn't use longer strings (sum of their utf8 byte lengths) that would fit into our buffer.
As a bonus, we could add utf8 string caching on top of this - there will be plenty of shared strings between rendered frames (assuming gui doesn't change rapidly), so it would avoid most of the string->utf8 conversions.
I updated the gist with changes: https://gist.github.com/dpethes/46f08c88bac0822fda05db4152fd00b2

And thanks a lot for hanging with me on this issue!

**Comment by dpethes** [comment]
I played with it a bit and seems to be working fine, however I haven't tried in a larger/more demanding app nor run it longer than 10 minutes. If you want to try it out, it's in this branch: https://github.com/dpethes/ImGui.NET/commits/utf8_conversions

**Comment by dpethes** [comment]
I rebased my utf8 branch on top of 1.50: https://github.com/dpethes/ImGui.NET/commits/utf8_conversions

**Comment by dpethes** [comment]
Rebased on top of 1.51.

**Comment by mellinoe** [comment]
The new 1.65.0 version has a much more robust string marshalling system. Auto-generating all of the marshalling code allows us to do pretty much whatever we want without having a big maintenance burden. I've tested and unicode strings are correctly marshalled and can be passed down to the native side.
