### ISSUE TITLE
Update to latest ImGui

### ISSUE THREAD

**Issue by Trojaner** [mellinoe/ImGui.NET#71]
ImGui gets updated very fast so this kinda got outdated already; as it does not include latest API's (like ImGuiSelectableFlags_Disabled: https://github.com/ocornut/imgui/commit/4e33aeed8285bb961ad5beb7b3bd251169bb7972)

**Comment by mellinoe** [comment]
I just pushed the previously-mentioned big overhaul, which brings ImGui.NET up to version 1.65. Going forward, it will be infinitely easier to keep things in sync.
