### ISSUE TITLE
PInvokeStackImbalance on ImGui.CreateContext()

### ISSUE THREAD

**Issue by Trojaner** [mellinoe/ImGui.NET#72]
Are the P/Invokes up to date?
Note: this started to happen after the autogen update

Additional information:
Program runs in x86 and x86 cimgui was used.
Issue happens at `ImGuiNET.ImGuiNative::igCreateContext`.

**Comment by mellinoe** [comment]
This should be fixed now, and a beta1 version was put on NuGet.
