### ISSUE TITLE
ImVector creation question

### ISSUE THREAD

**Issue by sonoro1234** [mellinoe/ImGui.NET#73]
Are you allocating ImVector?
For using in GlyphRangesBuilder::BuildRanges or TextRanges::split

Is this causing issues?
The problem I see is that Data memory is allocated, reallocated and freed by ImGui

**Comment by mellinoe** [comment]
I haven't tried to use that as of yet. You're probably right in that there are some memory ownership issues. Is it possible to give it an empty vector with a null allocation and then rely on it to resize it initially (and take over the memory)?

**Comment by sonoro1234** [comment]
I will try it.

**Comment by sonoro1234** [comment]
I am testing 
https://github.com/sonoro1234/cimgui/tree/GlyphRanges
only cimgui.cpp and cimgui.h manually edited
_init and _create version work for ImVector_ImWchar
I still dont know which is better

**Comment by sonoro1234** [comment]
Just incorporated ImVector templates C structs
