### ISSUE TITLE
Assertion failed: (g.IO.DisplaySize.x >= 0.0f && g.IO.DisplaySize.y >= 0.0f && "Invalid DisplaySize value")

### ISSUE THREAD

**Issue by Revolt64** [mellinoe/ImGui.NET#74]
Version - 0.4.7
Systems affected: Linux, Mac (works fine on windows)

Hey @mellinoe - hope you are well.
I'm testing a project that uses ImGui.NET successfully on Windows, however on Linux and Mac upon starting I'm greeted with the following assertion:

`Assertion failed: (g.IO.DisplaySize.x >= 0.0f && g.IO.DisplaySize.y >= 0.0f && "Invalid DisplaySize value"), function NewFrame, file ../imgui/imgui.cpp, line 2267.`

This problem has existed since at least v0.4.4, as I tested this some months ago with the same result.

Are you aware of this issue?
Thank you

**Comment by Revolt64** [comment]
That was exactly it, but in an interesting way.

This line:

`_imGuiIO.DisplaySize = new System.Numerics.Vector2(width, height);`

On windows it was fine to initialise this value in RenderDrawData(). However on Mac/Linux, it was needed inside my init function to setup ImGui. So before any drawing was done.

A slight qwirk. I guess Windows is just getting lucky as it seems logical that you would want to set the display size at initialisation time.

PS: The reason I update the value on every frame is so I can support window resizing.

Thanks again for the tip, which was obvious but I was too busy not seeing the wood due to all the trees.

**Comment by mellinoe** [comment]
That version of OpenTK is likely to cause a lot of problems, unfortunately. You should be able to step through the code to see whether any mouse clicks are actually making it into ImGui.NET.

**Comment by Revolt64** [comment]
After testing ImGui.Net in a MonoGame project and not having this issue, I can clearly see that it's that old OpenTK port to .NET core that is causing the issue.

Thanks again

Closing.
