### ISSUE TITLE
The XNA/MonoGame sample doesn't build

### ISSUE THREAD

**Issue by Revolt64** [mellinoe/ImGui.NET#75]
I'm incorporating the XNA/MonoGame ImGui.NET sample code into my blank MonoGame project.
I've added ImGui.NET 0.4.7 as a reference via Nuget and added the `import ImGui;` line at the top of the `ImGuiRender.cs` file.

I'm greeted with a slew of errors upon building however:

`private unsafe void RenderDrawData(ImDrawDataPtr drawData)`
"The type or namespace name 'ImDrawDataPtr' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (MonoBoy.Desktop)"

`var context = ImGui.CreateContext();
ImGui.SetCurrentContext(context);
`
"ImGui does not contain a definition for 'CreateContext()'"
"ImGui does not contain a definition for 'SetContext()'"

`var io = ImGui.GetIO();
io.Fonts.GetTexDataAsRGBA32(out byte* pixelData, out int width, out int height, out int bytesPerPixel);`

"IO does not contain a definition for 'Fonts"

There are more, but I think you get the picture.
Any ideas what's going on here?

**Comment by mellinoe** [comment]
The sample code that is in master now works with the 1.65.0-beta1 NuGet package, and isn’t compatible with the 0.x versions. You could either grab that version (which should be reasonably stable despite being a beta), or you could go back a few commits and grab the 0.x-compatible sample code.

Let me know if that helps.

**Comment by Revolt64** [comment]
I see what's going on now (I was actually "using" 1.65.0-beta1.

`Could not install package 'ImGui.NET 1.65.0-beta1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I forgot that ImGui.NET (your version) only targets .Net Core

**Comment by mellinoe** [comment]
ImGui.NET targets .NET Standard 2.0, not .NET Core. You can reference it from .NET Framework, mono, or .NET Core, but not such an old version of .NET Framework. You can just upgrade your target to netfx 4.7 and then install ImGui.NET. If it’s any encouragement, I don’t think .NET 4.5 is even supported anymore.
