### ISSUE TITLE
Broken input when built in release mode (Mac)

### ISSUE THREAD

**Issue by Revolt64** [mellinoe/ImGui.NET#76]
Hello @mellinoe 

I was having an issue where input (mouse clicks) was not working correctly in my project when built in release mode. I'm using MonoGame.

The clicks only semi-fire (and only if you rapid-click) and the ImGui display objects don't react to the click events when they do (they show the pressed state but nothing happens after).

I decided to see if I could re-create the issue using your XNA sample and experienced the same behaviour. When built in debug mode the problem does not exist.

I have attached the modified sample (to use the Nuget versions of ImGui.net & MonoGame) to demonstrate the issue. 

When building for release mode, I used the following command:

```dotnet build -c release -r osx-x64```

I included a built binary in the example that you can run also.

[ImGui.NET.SampleProgram.XNA.zip](https://github.com/mellinoe/ImGui.NET/files/2515086/ImGui.NET.SampleProgram.XNA.zip)

[Here's a video demonstrating the issue](https://youtu.be/dHQmGMsAgqw) (note the mouse clicks vs the input being received and not performing the button action).

- ImGui version: `1.65.0-beta1`
- MonoGame version: `3.7.0.7`

Could you look into this please as it's a big blocker for my project.
Thank you

**Comment by mellinoe** [comment]
I will assume this is the same as #63. The fix should be pretty simple, and I'll try to implement and share that tonight. In the meantime, you can try to follow what native imgui is doing [here](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_sdl.cpp#L213) to see if the problem gets fixed.

**Comment by Revolt64** [comment]
It could be related for sure.

But at you see in the video, the click events (when they do get through) don't execute the UI elements action. It's as if the click wasn't even done (bar the visual change).

Unless I frantically click, the UI elements don't even show their pressed/clicked state and when they do, the UI action (show/hide) doesn't get executed.

I really appreciate you looking into this.
Keep up the great work

**Comment by mellinoe** [comment]
Sorry, I didn't look closely enough at your video. There is something much more bizarre going on when I run that zip on macOS in Release mode. Notice that neither the window nor any of the buttons are focused when the clicks are happening -- they should get highlighted when the mouse is hovering them, regardless of the button state.

It seems to be an optimization issue because when I print `io.MousePos` to the console, the issue no longer occurs. I'll need some more time to look through this, unfortunately.

**Comment by Revolt64** [comment]
> It seems to be an optimization issue because when I print io.MousePos to the console, the issue no longer occurs

I tried that and can confirm that it no longer occurs when outputting mousepos to the console. 
Sounds like it's going to be tricky to diagnose...

Thanks for getting back to me so quickly 👍

**Comment by mellinoe** [comment]
I believe I have made a fix on the master branch. If you are able to pull that and test it, please let me know if the issue is gone.

**Comment by Revolt64** [comment]
@mellinoe thanks, i'll check it out and report back 👍

**Comment by Revolt64** [comment]
@mellinoe I'm having a bad time trying to get the project built on Mac Mojave.

- `cd` into `src` directory of ImGui.Net
- `dotnet build`
- output:

```
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /Users/username/Programming/Projects/External/ImGui.NET/src/CodeGenerator/CodeGenerator.csproj...
  Restoring packages for /Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET.SampleProgram/ImGui.NET.SampleProgram.csproj...
  Restoring packages for /Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET.SampleProgram.XNA/ImGui.NET.SampleProgram.XNA.csproj...
  Restoring packages for /Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET/ImGui.NET.csproj...
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/ImGui.NET/ImGui.NET.csproj.nuget.g.props.
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/CodeGenerator/CodeGenerator.csproj.nuget.g.props.
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/ImGui.NET/ImGui.NET.csproj.nuget.g.targets.
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/CodeGenerator/CodeGenerator.csproj.nuget.g.targets.
  Restore completed in 399.79 ms for /Users/username/Programming/Projects/External/ImGui.NET/src/CodeGenerator/CodeGenerator.csproj.
  Restore completed in 399.79 ms for /Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET/ImGui.NET.csproj.
  Installing MonoGame.Framework.DesktopGL 3.6.0.1625.
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/ImGui.NET.SampleProgram.XNA/ImGui.NET.SampleProgram.XNA.csproj.nuget.g.props.
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/ImGui.NET.SampleProgram.XNA/ImGui.NET.SampleProgram.XNA.csproj.nuget.g.targets.
  Restore completed in 37.48 sec for /Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET.SampleProgram.XNA/ImGui.NET.SampleProgram.XNA.csproj.
  Installing Microsoft.DotNet.PlatformAbstractions 2.0.3.
  Installing Microsoft.Extensions.DependencyModel 2.0.3.
  Installing SharpDX.Direct3D11 4.0.1.
  Installing SharpDX 4.0.1.
  Installing SharpDX.DXGI 4.0.1.
  Installing NativeLibraryLoader 1.0.10.
  Installing SharpDX.D3DCompiler 4.0.1.
  Installing Veldrid.OpenGLBindings 4.3.3.
  Installing Vk 1.0.19.
  Installing Veldrid.MetalBindings 4.3.3.
  Installing Veldrid.SDL2 4.3.3.
  Installing Veldrid.StartupUtilities 4.3.3.
  Installing Veldrid 4.3.3.
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/ImGui.NET.SampleProgram/ImGui.NET.SampleProgram.csproj.nuget.g.props.
  Generating MSBuild file /Users/username/Programming/Projects/External/ImGui.NET/bin/obj/ImGui.NET.SampleProgram/ImGui.NET.SampleProgram.csproj.nuget.g.targets.
  Restore completed in 1.06 min for /Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET.SampleProgram/ImGui.NET.SampleProgram.csproj.
/usr/local/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET.SampleProgram.XNA/ImGui.NET.SampleProgram.XNA.csproj]
  CodeGenerator -> /Users/username/Programming/Projects/External/ImGui.NET/bin/Debug/CodeGenerator/netcoreapp2.1/CodeGenerator.dll
  ImGui.NET -> /Users/username/Programming/Projects/External/ImGui.NET/bin/Debug/ImGui.NET/netstandard2.0/ImGui.NET.dll
  ImGui.NET.SampleProgram -> /Users/username/Programming/Projects/External/ImGui.NET/bin/Debug/ImGui.NET.SampleProgram/netcoreapp2.0/ImGui.NET.SampleProgram.dll

Build FAILED.

/usr/local/share/dotnet/sdk/2.1.403/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/username/Programming/Projects/External/ImGui.NET/src/ImGui.NET.SampleProgram.XNA/ImGui.NET.SampleProgram.XNA.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:01:11.49
```

-- I'm not quite understanding that build error, as I don't see anything referencing `.NET 4.6.2`?

**Comment by Revolt64** [comment]
I figured out it was the XNA/MonoGame sample from building and it build successfully. I'll give it a whirl  now.

**Comment by Revolt64** [comment]
@mellinoe Ok so I tested it and it works fine now in release mode.

Could I push my luck and ask for a new Nuget version? I prefer using those to linking against the github project.

Thank you for the quick fix!

**Comment by mellinoe** [comment]
I was just waiting for confirmation that the fix worked. I’ll put out a new version tonight.

**Comment by mellinoe** [comment]
@Revolt64 There is a beta2 package out now: https://www.nuget.org/packages/ImGui.NET/1.65.0-beta2

**Comment by Revolt64** [comment]
Beta2 works like a charm.

Thanks again!
