### ISSUE TITLE
Font loading from TTF not working in latest beta

### ISSUE THREAD

**Issue by Revolt64** [mellinoe/ImGui.NET#77]
Hey @mellinoe, sorry for piling on the bugs lately!

I'm using the latest beta of ImGui, and am loading a font via:

```csharp
ImGui.GetIO().Fonts.AddFontFromFileTTF($"fonts\\ComicSansMS.ttf", 14.0f);
```
Using comic sans as it's the most obvious to see if the font changed successfully, from a visual perspective. The call to AddDefaultFont() is commented out.

- Expected outcome: text displayed using the comic sans font.
- Actual outcome: text displayed using the default ImGui font.

I used the same example as I did in [this bug report](https://github.com/mellinoe/ImGui.NET/issues/76) (your Monogame sample, but using the Nuget packages), with the only change being adding the font, a post build step to copy the fonts to the bin directory and the call to `AddFrontFromFileTTF()`.

Loading a ttf font worked fine for me before switching to the beta version of ImGui. I've already committed to changing my code to use the new ImGui beta, so I'd prefer to stick with it, as the changes in the beta are great.

- ImGui version: `1.65.0-beta1`
- MonoGame version: `3.7.0.7`

[ImGui.NET.SampleProgram.XNA_Font_Issue.zip](https://github.com/mellinoe/ImGui.NET/files/2516394/ImGui.NET.SampleProgram.XNA_Font_Issue.zip)

Thank you

**Comment by mellinoe** [comment]
Hm, it seems to work for me when I try it in the sample:

![image](https://user-images.githubusercontent.com/8918977/47540543-9152a880-d88a-11e8-8664-d6fe7cda89d2.png)

```C#
ImGui.GetIO().Fonts.AddFontFromFileTTF(@"C:\Windows\Fonts\Arial.ttf", 12f);
//ImGui.GetIO().Fonts.AddFontDefault();
```

**Comment by Revolt64** [comment]
hmm, it actually does work now.

Turned out it was my fault. 
Is there any way the `AddFontFromFileTTF` function could log to the console or throw an exception if the font file isn't found at the path?

This is what threw me off, as there are no error messages when it fails to find a font.

**Comment by mellinoe** [comment]
> Is there any way the AddFontFromFileTTF function could log to the console or throw an exception if the font file isn't found at the path?

It's difficult to inject that kind of custom code into the generated output, but there could be room in the library for manual overloads like that, defined in [ImGui.Manual.cs](https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/ImGui.Manual.cs)
