### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by wizzard0** [mellinoe/ImGui.NET#8]
what's the license for this repo?

i'm willing to <-> integrate between [my imgui wrapper](https://github.com/AlgoTradingHub/imgui_rt) which also boasts software rendering support, but I need the license to be MIT so I can reuse this for my dayjob

**Comment by mellinoe** [comment]
I've been meaning to put up the MIT license for the project. @dpethes , do you have any objections to that? You and I are the only contributors at this point.

**Comment by dpethes** [comment]
Fine by me.

**Comment by wizzard0** [comment]
Thanks a lot!

Um, and could you please add the license file then? :)

**Comment by mellinoe** [comment]
@wizzard0 Yes, sorry 😄. I will add it later today.

**Comment by mellinoe** [comment]
https://github.com/mellinoe/ImGui.NET/commit/7cc420b16bc540beb0930714239b7437dad2d5e5
