### ISSUE TITLE
Program crashes when reaching 31 > characters in InputText

### ISSUE THREAD

**Issue by tienery** [mellinoe/ImGui.NET#80]
Now that I have my program working (sort of), I now have stumbled across a peculiar and **proper** error when debugging.

When typing anymore than 31 characters into `InputText`, the program crashes. Instead of Visual Studio actually capturing this error, Windows instead props up the following dialog:

![image](https://user-images.githubusercontent.com/2475112/47622566-50fb6080-dafe-11e8-8cb4-2b50eb023929.png)

This suggests to me that the extern code itself is broken, such as say the C/C++ code of dear imgui. However, that being said, I cannot find any issues on the dear imgui side of things relating to this crash or error. So, maybe my Visual Studio is playing up?

I am using the following code for one of my Input Text:

```c#
if (ImGui.InputText("##Description", chapterData[currentChapter].Description, 255, ImGuiInputTextFlags.EnterReturnsTrue))
                        {
                            chapterData[currentChapter].Update();
                        }
```

One thing to note is that you can set the value of the string programmatically to being greater than 31 characters and be able to edit the text as normal. However, in testing this it also appears the `string` is not being updated properly.

I don't know what it is but there seems to be something seriously wrong with the generated code. Perhaps `ref string` should be used than just `string` to ensure the string is actually updated. As for the reason why I crash after inputting more than 31 characters fresh into an `InputText` I have no clue. I would have to dig a bit more.

Any help would be appreciated.

**Comment by mellinoe** [comment]
@tienery I've pushed a new commit to master which replaces the auto-generated overloads for ImGui.InputText with versions as described above. The second parameter is a by-ref string which is only reassigned with a newly-constructed string when it is actually edited.

Let me know if you're able to try it out.

**Comment by tienery** [comment]
Having a go this morning, and it's working like a charm. Will let you know if there's any performance issues later down the line as I start working with multiline and larger volumes of text.
