### ISSUE TITLE
Got a Problem with the ImGui.Net

### ISSUE THREAD

**Issue by TezzoeR** [mellinoe/ImGui.NET#83]
If i try to debug my programm i get this error

System.DllNotFoundException: 'Unable to load DLL 'cimgui': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

**Comment by mellinoe** [comment]
Hey @TezzoeR , could you provide more information about what operating system and runtime (.NET Framework, .NET Core, or mono) you are using?

There are a couple of known issues with .NET Framework and mono. If you're using .NET Framework, you need to target a specific platform in your project, e.g. x64 or x86. This can be done through the project properties window in Visual Studio.

If you're using mono, unfortunately it doesn't understand how to locate the native dependencies that are bundled with the NuGet package. You have to manually add them to your project and tell it to copy them to the output directory.

**Comment by turbo** [comment]
Just to answer this question, Mono either needs a DLL map, or you need to rename the binary. By default, it looks for `libcimgui.so` in the output dir (mind the "lib" part).

**Comment by mellinoe** [comment]
Yes, what @turbo said is also correct, as I recently discovered. Mono won't automatically add the "lib" prefix as CoreCLR does, so something needs to be done about that. I will likely add a DllMap file to the package at some point, but you will still need to manually copy the cimgui binary to your output directory, as far as I know.

**Comment by roy-t** [comment]
I'd just like to chime in that this doesn't seem to work out of the box for my config.  So to me it doesn't seem related to Mono.

I've added the NuGet package to my 64bit .Net Framework 4.7.2 application (on Windows) and the cimgui.dll is not copied automatically to the output directory.

**Comment by amerkoleci** [comment]
Take look at veldrid-spirv package, there is .targets file that copy the native libs

**Comment by zeropointx** [comment]
I got same issue. I managed to copy 64 and 32 bit dll but then I got "System.AccessViolationException: Attempted to read or write protected memory." on both.

**Comment by mellinoe** [comment]
> I got same issue. I managed to copy 64 and 32 bit dll but then I got "System.AccessViolationException: Attempted to read or write protected memory." on both.

That's a different issue, likely related to not calling functions in the correct order. Double-check your initialization steps and make sure they are doing what the samples are doing.

**Comment by zeropointx** [comment]
> > I got same issue. I managed to copy 64 and 32 bit dll but then I got "System.AccessViolationException: Attempted to read or write protected memory." on both.
> 
> That's a different issue, likely related to not calling functions in the correct order. Double-check your initialization steps and make sure they are doing what the samples are doing.

I checked and yeah that seems to be the issue I am having now. So copying it manually from nuget package folder seems to fix original issue (dll not found).
