### ISSUE TITLE
AccessViolationException on initialize

### ISSUE THREAD

**Issue by NotHunter101** [mellinoe/ImGui.NET#85]
![image](https://user-images.githubusercontent.com/35887932/49084691-2fd18100-f21e-11e8-85d4-435181bef85f.png)

**Comment by NotHunter101** [comment]
I pretty much just copied the stock XNA example code into my project. What version of the ImGUI.Net.DLL should I be using, and how would I obtain it? I have a feeling that this is to due with me just having the wrong DLLs.

Operating System: Windows 10 x64
.Net Framework 4.7.2

**Comment by NotHunter101** [comment]
Okay, apparently I was using the wrong cimgui. Now that I am using the right one, the application boots, but nothing draws. Any ideas?

**Comment by mellinoe** [comment]
Are you running the sample program, or your own project? If the latter, what modifications have you made?

**Comment by NotHunter101** [comment]
I am using my own project, but I essentially copied the code directly from the sample. When I get home I will loading the sample project directly.

**Comment by NotHunter101** [comment]
I got this to work, I was using the wrong references and targeting the wrong framework version. Thanks for your help.
