### ISSUE TITLE
Sample hangs on close when using latest monogame version (3.7)

### ISSUE THREAD

**Issue by tbolon** [mellinoe/ImGui.NET#86]
If you update the monogame package to the latest version (3.7), the sample hangs when closing the window.

Even removing all the code in ImgUILayout() did not solve the problem.

I think the code is missing code for releasing resources.

**Comment by mellinoe** [comment]
@flyingpie Any idea what could be happening here? Perhaps some sort of missing cleanup call that is needed in 3.7?

**Comment by flyingpie** [comment]
@mellinoe I've updated the sample to use MonoGame 3.7, including a fix for the aforementioned issue. Turns out the Game-object wasn't being disposed.

@tbolon Could you let me know if this fixes your problem?

https://github.com/mellinoe/ImGui.NET/pull/87
