### ISSUE TITLE
FontAtlas issue

### ISSUE THREAD

**Issue by Eliminster0** [mellinoe/ImGui.NET#9]
So when I call NewFrame I make it to line 2133 in imgui.cpp before it throws an exception:

`IM_ASSERT(g.IO.Fonts->Fonts[0]->IsLoaded());`
`// Font Atlas not created. Did you call io.Fonts->GetTexDataAsRGBA32 / GetTexDataAsAlpha8 ?`

In the ImGui fonts readme it states:

> The code in imgui.cpp embeds a copy of 'ProggyClean.ttf' that you can use without any external files.
 The files in this folder are only provided as a convenience, you can use any of your own .TTF files.
>
>Fonts are rasterized in a single texture at the time of calling either of io.Fonts.GetTexDataAsAlpha8()/GetTexDataAsRGBA32()/Build().
>
>#########################
> FONTS LOADING INSTRUCTIONS
>#########################
>
>Load default font with:
>
> ImGuiIO& io = ImGui::GetIO();
> io.Fonts->AddFontDefault();

It seems ( I could be totally wrong) that in the sample this was achieved by:

`ImGui.GetIO().FontAtlas.AddDefaultFont();`

However the most recent version no longer has this method. I did notice that ImGui does have `LoadDefaultFont()`. I am unsure if this is meant to serve the same purpose, however, it did not seem to fix the issue. Thanks for any guidance, and awesome job on creating this.

**Comment by mellinoe** [comment]
Hey @Eliminster0 , `FontAtlas.AddDefaultFont()` does still exist, and should be what you use to load the default "ProggyClean" font. You can alternatively use one of the other font loading functions to load a different font from disk, for example.

https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/IO.cs#L262

You might have gotten a bit mixed up because it is in the `IO.cs` file, and the `FontAtlas` file actually has the `NativeFontAtlas` structure (which is what `FontAtlas` wraps). I will clean that up so it is less confusing.

**Comment by Eliminster0** [comment]
@mellinoe, you are correct that `FontAtlas.AddDefaultFont()` does still exist. It appears that there was an issue with the DLL that was created when adding ImGui.Net to an existing project via NuGet. I instead had to clone the repo, build the DLL, and swap out the DLLs. 

I am unsure if this maybe just an isolated issue unique to myself or something else.

Thanks again :D

**Comment by dpethes** [comment]
The nuget version was quite outdated the last time I tried.

**Comment by mellinoe** [comment]
Yeah, the nuget version is quite outdated. Personally, I prefer to include the project as a submodule myself, but I know others probably don't like that workflow. I will update the version on NuGet shortly.

**Comment by mellinoe** [comment]
I published a version 0.1.6 here: https://www.nuget.org/packages/ImGui.NET/0.1.6.

Note that I produced this from the [drawlist branch](https://github.com/mellinoe/ImGui.NET/tree/drawlist). It has a few things over what is in master, namely some wrappers for ImDrawList stuff.
