### ISSUE TITLE
XNA and Input Text

### ISSUE THREAD

**Issue by Hi-ImKyle** [mellinoe/ImGui.NET#90]
Hey, I'm just trying to get a simple input text box to work in a XNA environment but for some reason the input box only accepts backspace. Not only is backspace only a issue, whenever I go to focus the input the last letter of the buffer always gets deleted once.

Text refusing to exist (note to check keys down I'm using the XNA Keyboard class):
![Text Refusing Issue](https://user-images.githubusercontent.com/25551312/49763224-f68c1d00-fcc3-11e8-930d-2c31ba1a1500.gif)

Last character disappearing:
![Text Disappearing Issue](https://user-images.githubusercontent.com/25551312/49763225-f68c1d00-fcc3-11e8-872e-51bbd9a44c46.gif)

If you're wondering the game, it's [Terraria](https://store.steampowered.com/app/105600/Terraria/), I'm trying to client for admins/moderators, doing things in chat like commands n stuff just seems overrated. I like a nice clean UI to do things, figured I'd try and make one.

I was thinking maybe the game is blocking input but I've checked and there doesn't appear to be anything preventing imgui from getting keyboard input from XNA, if it is doing that anyway. 

Less of an issue and more of just asking if anyone knows what could be preventing imgui from getting input and a possible fix.

**Comment by mellinoe** [comment]
Does your code differ significantly from the example project here? Text input fields work properly in the sample code, so there is likely something wrong with how you are sending inputs into ImGui from your project.

**Comment by Hi-ImKyle** [comment]
As far as I'm concerned, you're not sending any inputs to ImGui in the sample project anyway? Plus I don't own Terraria's code so if anything there'll be something in there preventing ImGui from picking up the keystrokes, but I figured if anything, if ImGui can catch a backspace it can catch the rest.

**Comment by mellinoe** [comment]
Here's where the text input is set up:
https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram.XNA/ImGuiRenderer.cs#L168-L184

And here's where the per-frame input is sent:
https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET.SampleProgram.XNA/ImGuiRenderer.cs#L219

**Comment by Hi-ImKyle** [comment]
Well that class is included and is being called as far as I'm concerned. I've even changed the 4th line in UpdateInput() to use the game's keystate field instead of the direct XNA one and it's still only accepting backspace.

**Comment by mellinoe** [comment]
I'm not familiar enough with the differences / compatibility between XNA and MonoGame to answer that exactly, but it's likely you just need to change some namespaces, or maybe fully-qualify some of the uses of different types. You probably don't want to be referencing MonoGame.Framework at the same time as XNA.Framework -- one or the other. Again, though, not an expert on that.

**Comment by Hi-ImKyle** [comment]
There is a possible fix, Reference Aliases but that just leads to more issues. I'll just see if I can find another way. Thanks anyway.
