### ISSUE TITLE
How to setup new project with ImGUI.NET

### ISSUE THREAD

**Issue by thgiang** [mellinoe/ImGui.NET#99]
I am sorry for noob question. But I don't know to to start a new project with IAMGUI.

I has a Window Form Application. My form has 1 button named "Click to show IAMGUI"
This is my project structure: http://prntscr.com/m3al3h

When try to run my project, it show this error on IamGuiControler.cs
http://prntscr.com/m3al8n

Do I missing something? Please help me. Thank you <3

**Comment by thgiang** [comment]
Now I know how to fix it. Right click to resource file choose Properties then setup as image.
http://prntscr.com/m3atiu

**Comment by mellinoe** [comment]
@thgiang An easier way to set things up is to reference the NuGet package. It will include stuff like shaders automatically.
